import type { WorkflowGraph, WorkflowGraphNode } from "@/lib/contracts/workflow-graph";
import { graphObject } from "./graph-schema";
import { workflowPath } from "./graph-bindings";
export type FlowNodeResult={output:unknown;handles?:string[];log?:string};
function items(config:Record<string,unknown>,runtime:unknown){const raw=Array.isArray(config.items)?config.items:typeof config.itemsPath==="string"?workflowPath(runtime,config.itemsPath):[];if(!Array.isArray(raw))throw new Error("workflow items must resolve to an array");if(raw.length>1000)throw new Error("workflow item limit is 1000");return raw;}
export async function executeFlowNode(node:WorkflowGraphNode,config:Record<string,unknown>,graph:WorkflowGraph,outputs:Record<string,unknown>,runtime:unknown):Promise<FlowNodeResult|null>{
 if(node.type==="condition"){const ref=typeof config.path==="string"?config.path:"input",value=workflowPath(runtime,ref),branch=Object.hasOwn(config,"equals")?JSON.stringify(value)===JSON.stringify(config.equals):Boolean(value);return{output:{value,branch},handles:[String(branch)],log:`Condition evaluated to ${branch}.`};}
 if(node.type==="switch"){const ref=typeof config.path==="string"?config.path:"input",value=workflowPath(runtime,ref),cases=Array.isArray(config.cases)?config.cases:[],handles:string[]=[];for(let i=0;i<Math.min(32,cases.length);i++){const row=cases[i];if(!graphObject(row))continue;const handle=typeof row.handle==="string"&&row.handle?row.handle:`case-${i+1}`;if(Object.hasOwn(row,"equals")&&JSON.stringify(value)===JSON.stringify(row.equals))handles.push(handle);}if(!handles.length)handles.push("default");return{output:{value,handles},handles,log:`Switch selected ${handles.join(", ")}.`};}
 if(node.type==="merge"){const incoming=graph.edges.filter((edge)=>!edge.disabled&&edge.target===node.id).map((edge)=>({source:edge.source,value:outputs[edge.source]}));const mode=String(config.mode??"combine");let output:unknown;if(mode==="append")output=incoming.flatMap((row)=>Array.isArray(row.value)?row.value:[row.value]);else if(mode==="passThrough")output=incoming.at(-1)?.value??null;else output=Object.fromEntries(incoming.map((row)=>[row.source,row.value]));return{output,log:`Merged ${incoming.length} incoming branch(es) using ${mode}.`};}
 if(node.type==="batch"){const all=items(config,runtime),size=Math.max(1,Math.min(1000,Math.trunc(Number(config.size)||10))),batches=[];for(let i=0;i<all.length;i+=size)batches.push(all.slice(i,i+size));return{output:{items:all,batches,count:batches.length,size},log:`Split ${all.length} item(s) into ${batches.length} batch(es).`};}
 if(node.type==="wait"){const until=typeof config.until==="string"?Date.parse(config.until):NaN,delay=Number.isFinite(until)?until-Date.now():Number(config.delayMs??0),ms=Math.max(0,Math.min(10*60_000,Math.trunc(delay)||0));if(delay>10*60_000)throw new Error("wait node maximum is 10 minutes per run");if(ms)await new Promise((resolve)=>setTimeout(resolve,ms));return{output:{waitedMs:ms,resumedAt:new Date().toISOString()},log:`Waited ${ms}ms.`};}
 return null;
}
export function workflowItems(config:Record<string,unknown>,runtime:unknown){return items(config,runtime);}
