import { createResolvedJevWorkflowOptimizerEvaluator } from "./jev-evaluator";
import { resolveJevIntegrationConfig, type JevIntegrationInput } from "./jev-integration";
import type { CapabilityTool, CapabilityRunContext } from "@/lib/capabilities/tool";
import { executeCapabilityCall } from "@/lib/capabilities/execute";

export type JevActionCandidate = { id:string; tool:string; arguments:Record<string,unknown>; rationale:string; risk:"safe"|"review"|"destructive" };
export type JevActionProposal = { kind:"mso.jev-action-proposal.v1"; provider:"jev"; selected:Array<JevActionCandidate & { probability:number }>; rejected:Array<{id:string;probability:number}>; executable:false; instruction:string };

const FORBIDDEN = new Set(["exec_run","exec_job_start","fs_delete","fs_write","fs_upload_file","fs_move","fs_copy","tool_forge_promote","agent_memory_forget","workflow_cancel"]);
const SECRET_KEY = /(?:secret|token|password|api[_-]?key|authorization|cookie)/i;
function clean(value:unknown, depth=0):unknown { if(depth>5)return "[bounded]"; if(Array.isArray(value))return value.slice(0,32).map(v=>clean(v,depth+1)); if(!value||typeof value!=="object")return typeof value==="string"?value.slice(0,4000):value; const out:Record<string,unknown>={}; for(const [k,v] of Object.entries(value as Record<string,unknown>)){ if(SECRET_KEY.test(k))continue; out[k]=clean(v,depth+1); } return out; }
export function validateJevActionCandidates(rows:JevActionCandidate[], resolveTool:(name:string)=>CapabilityTool|undefined){ return rows.slice(0,16).map(row=>{ const tool=resolveTool(row.tool); if(!tool) throw new Error(`JEV action references unknown tool: ${row.tool}`); if(FORBIDDEN.has(row.tool)) throw new Error(`JEV action tool is not eligible for autonomous proposal: ${row.tool}`); return {...row,arguments:clean(row.arguments) as Record<string,unknown>,risk:tool.annotations?.destructiveHint?"destructive":row.risk}; }); }
export async function proposeJevActions(state:Record<string,unknown>, rows:JevActionCandidate[], resolveTool:(name:string)=>CapabilityTool|undefined, jev?:JevIntegrationInput):Promise<JevActionProposal>{ const safe=validateJevActionCandidates(rows,resolveTool); const candidates=safe.map(row=>({id:row.id,kind:"presentation-group" as const,hostEligible:true as const,title:`Call ${row.tool}`,description:row.rationale,nodeIds:[],estimatedNodeDelta:0,risk:row.risk==="safe"?"safe" as const:"review" as const})); const evaluation=await createResolvedJevWorkflowOptimizerEvaluator(await resolveJevIntegrationConfig(jev))(clean(state) as Record<string,unknown>,candidates); const selected=safe.map(row=>({...row,probability:evaluation.probabilities[row.id]??0})).filter(row=>row.probability>=.5).sort((a,b)=>b.probability-a.probability); const chosen=new Set(selected.map(row=>row.id)); return {kind:"mso.jev-action-proposal.v1",provider:"jev",selected,rejected:safe.filter(row=>!chosen.has(row.id)).map(row=>({id:row.id,probability:evaluation.probabilities[row.id]??0})),executable:false,instruction:"JEV selected structured action candidates only. Re-check live state and use jev_action execute explicitly; MSO capability scope, workflow, token allowlists, argument constraints, rate limits and audit remain authoritative."}; }
export async function executeJevAction(proposal:JevActionProposal, actionId:string, input:{scope:CapabilityRunContext["scope"];actor?:string;context?:CapabilityRunContext}, resolveTool:(name:string)=>CapabilityTool|undefined){ const action=proposal.selected.find(row=>row.id===actionId); if(!action) throw new Error("JEV action was not selected in this proposal"); const tool=resolveTool(action.tool); if(!tool) throw new Error("JEV action tool is no longer available"); if(tool.annotations?.destructiveHint || action.risk!=="safe") throw new Error("JEV action requires normal explicit tool confirmation; proposal cannot auto-execute it"); return executeCapabilityCall({tool,args:action.arguments,scope:input.scope,actor:input.actor,context:input.context}); }
