import { beforeEach, describe,it,expect,vi } from "vitest";
const {evaluate,executeCapabilityCall,verify}=vi.hoisted(()=>({evaluate:vi.fn(),executeCapabilityCall:vi.fn(),verify:vi.fn()}));
vi.mock("./jev-decision-plane",()=>({createJevDecisionEvaluator:()=>evaluate}));
vi.mock("@/lib/capabilities/execute",()=>({executeCapabilityCall}));
vi.mock("./jev-services",()=>({verifyActionOutcomeWithJev:verify}));
vi.mock("./jev-telemetry",()=>({recordJevTelemetry:vi.fn(async()=>undefined)}));
import { proposeJevActions,executeJevAction,clearJevActionProposalsForTests } from "./jev-action-layer";
const tool=(name:string,scope:"read"|"write"|"exec"="read",destructive=false)=>({name,scope,description:name,inputSchema:{type:"object" as const,properties:{}},annotations:{destructiveHint:destructive,readOnlyHint:scope==="read"},run:async()=>({})});
beforeEach(()=>{clearJevActionProposalsForTests();vi.useRealTimers();evaluate.mockReset();executeCapabilityCall.mockReset();verify.mockReset();evaluate.mockResolvedValue({provider:"jev",probabilities:{a:.91},jev:{model:"typesafe/jev-1.13",latencyMs:5,inputTokens:12,actualCostUsd:.000001}});executeCapabilityCall.mockResolvedValue({kind:"success",result:{ok:true}});verify.mockResolvedValue({verification:"pass",provider:"jev"});});
describe("JEV action layer",()=>{
 it("produces a non-executable server-held proposal and strips secret-shaped arguments",async()=>{const p=await proposeJevActions({token:"hidden",ok:"yes"},[{id:"a",tool:"sys_stats",arguments:{apiKey:"hidden",x:"ok"},rationale:"inspect health",risk:"safe"}],n=>n==="sys_stats"?tool(n):undefined);expect(p).toMatchObject({kind:"mso.jev-action-proposal.v1",provider:"jev",executable:false,selected:[{id:"a",tool:"sys_stats",probability:.91,arguments:{x:"ok"}}]});expect(p.proposalId).toMatch(/^jev_/);expect(JSON.stringify(p)).not.toContain("hidden");});
 it("rejects unknown and arbitrary executor candidates before JEV without executing",async()=>{const p=await proposeJevActions({},[{id:"a",tool:"exec_run",arguments:{command:"id"},rationale:"x",risk:"safe"},{id:"b",tool:"missing",arguments:{},rationale:"x",risk:"safe"}],n=>n==="exec_run"?tool(n,"exec",true):undefined);expect(p.selected).toEqual([]);expect(p.rejected).toEqual(expect.arrayContaining([expect.objectContaining({id:"a",reason:expect.stringContaining("not eligible")}),expect.objectContaining({id:"b",reason:"unknown capability"})]));expect(evaluate).not.toHaveBeenCalled();expect(executeCapabilityCall).not.toHaveBeenCalled();});
 it("executes only a selected safe read through capability authority then verifies the bounded result",async()=>{const p=await proposeJevActions({},[{id:"a",tool:"sys_stats",arguments:{x:"ok"},rationale:"health",risk:"safe"}],n=>n==="sys_stats"?tool(n):undefined);const context={scope:"read" as const,allowedTools:["sys_stats"],workflowId:"wf-1"};const out=await executeJevAction(p.proposalId,"a",{scope:"read",actor:"tester",context},n=>n==="sys_stats"?tool(n):undefined);expect(out).toMatchObject({kind:"mso.jev-action-result.v1",proposalId:p.proposalId,actionId:"a",execution:{kind:"success"},verification:{verification:"pass"}});expect(executeCapabilityCall).toHaveBeenCalledWith(expect.objectContaining({args:{x:"ok"},scope:"read",actor:"tester",context}));expect(verify).toHaveBeenCalledWith("health",{kind:"success",result:{ok:true}},undefined,expect.objectContaining({workflowRef:"wf-1"}));});
 it("keeps selected write/review actions review-only",async()=>{const p=await proposeJevActions({},[{id:"a",tool:"project_mcp_call",arguments:{},rationale:"call",risk:"safe"}],n=>n==="project_mcp_call"?tool(n,"exec"):undefined);expect(p.selected[0]?.risk).toBe("review");await expect(executeJevAction(p.proposalId,"a",{scope:"exec",context:{scope:"exec"}},n=>n==="project_mcp_call"?tool(n,"exec"):undefined)).rejects.toThrow("normal explicit tool confirmation");expect(executeCapabilityCall).not.toHaveBeenCalled();});
 it("rejects stale capability contracts, unknown proposal ids, and action-id mismatch",async()=>{const p=await proposeJevActions({},[{id:"a",tool:"sys_stats",arguments:{},rationale:"health",risk:"safe"}],n=>n==="sys_stats"?tool(n):undefined);await expect(executeJevAction("jev_missing","a",{scope:"read",context:{scope:"read"}},n=>n==="sys_stats"?tool(n):undefined)).rejects.toThrow("missing or expired");await expect(executeJevAction(p.proposalId,"b",{scope:"read",context:{scope:"read"}},n=>n==="sys_stats"?tool(n):undefined)).rejects.toThrow("action id was not selected");const changed={...tool("sys_stats"),inputSchema:{type:"object" as const,properties:{mode:{type:"string"}},required:["mode"]}};await expect(executeJevAction(p.proposalId,"a",{scope:"read",context:{scope:"read"}},n=>n==="sys_stats"?changed:undefined)).rejects.toThrow("capability contract changed");});
 it("expires proposals instead of silently executing stale decisions",async()=>{vi.useFakeTimers();vi.setSystemTime(new Date("2026-09-26T00:00:00Z"));const p=await proposeJevActions({},[{id:"a",tool:"sys_stats",arguments:{},rationale:"health",risk:"safe"}],n=>n==="sys_stats"?tool(n):undefined);vi.advanceTimersByTime(10*60_000+1);await expect(executeJevAction(p.proposalId,"a",{scope:"read",context:{scope:"read"}},n=>n==="sys_stats"?tool(n):undefined)).rejects.toThrow("missing or expired");});
});
