import type { WorkflowGraphNodeType } from "@/lib/contracts/workflow-graph";
export type WorkflowNodeCatalogItem={type:WorkflowGraphNodeType;title:string;category:string;description:string;handles?:string[];defaults:Record<string,unknown>};
export const WORKFLOW_NODE_CATALOG:WorkflowNodeCatalogItem[]=[
 {type:"manual",title:"Manual Trigger",category:"Triggers",description:"Start from UI, CLI or MCP.",defaults:{}},
 {type:"schedule",title:"Schedule Trigger",category:"Triggers",description:"Run by cron or minute interval on the MSO server.",defaults:{mode:"interval",everyMinutes:60}},
 {type:"webhook",title:"Webhook Trigger",category:"Triggers",description:"Public HTTP trigger with optional private-variable bearer auth.",defaults:{methods:["POST"],responseMode:"onReceived"}},
 {type:"condition",title:"If",category:"Flow",description:"Route to true/false handles.",handles:["true","false"],defaults:{path:"input"}},
 {type:"switch",title:"Switch",category:"Flow",description:"Route by multiple case handles plus default.",defaults:{path:"input",cases:[]}},
 {type:"merge",title:"Merge",category:"Flow",description:"Merge enabled incoming node outputs.",defaults:{mode:"combine"}},
 {type:"batch",title:"Split In Batches",category:"Flow",description:"Chunk an array into deterministic batches.",defaults:{size:10}},
 {type:"loop",title:"Loop Over Items",category:"Flow",description:"Run one bounded tool once per item without cyclic graph edges.",defaults:{concurrency:1}},
 {type:"repeat",title:"Repeat Until",category:"Flow",description:"Run a saved workflow repeatedly until its output matches a condition or a hard iteration/time limit is reached.",handles:["done","exhausted"],defaults:{input:{},path:"result.output",equals:true,maxIterations:5,delayMs:1000,maxDurationMs:600000}},
 {type:"wait",title:"Wait",category:"Flow",description:"Delay execution or wait until a timestamp within run timeout.",defaults:{delayMs:1000}},
 {type:"cache",title:"Cache",category:"Context",description:"Read/write/delete a private principal-scoped TTL cache for reusable workflow data.",defaults:{mode:"get_or_set",ttlSeconds:300,key:"workflow-cache"}},
 {type:"memory",title:"Memory",category:"Context",description:"Read/search/remember MSO agent memory or repo-local project memory.",defaults:{scope:"agent",mode:"search",query:""}},
 {type:"session",title:"Session",category:"Context",description:"Read current durable session, list/resume sessions, or attach a durable note.",defaults:{mode:"current"}},
 {type:"directory",title:"Directory",category:"Context",description:"Discover MSO tools, workflows, sessions, projects or skills at runtime.",defaults:{source:"tools",query:"",limit:30}},
 {type:"tool",title:"MSO Tool",category:"Actions",description:"Call one bounded MSO capability tool.",defaults:{}},
 {type:"project_function",title:"Project Function",category:"Actions",description:"Call a project-owned function.",defaults:{}},
 {type:"project_mcp",title:"Project MCP",category:"Actions",description:"Call a project-owned MCP tool.",defaults:{}},
 {type:"integration",title:"Integration",category:"Actions",description:"Execute through an existing MSO integration connection; credentials stay outside the graph.",defaults:{}},
 {type:"script",title:"Script",category:"Actions",description:"Run a saved validated RASMIC script by project and script id.",defaults:{}},
 {type:"agent",title:"Agent",category:"AI",description:"Run an organization seat or focused project agent action.",defaults:{wait:true,max_scope:"write"}},
 {type:"subflow",title:"Subflow",category:"Flow",description:"Run an existing project flow.",defaults:{}},
 {type:"project",title:"Project",category:"Context",description:"Resolve canonical project identity/path at runtime.",defaults:{}},
 {type:"folder",title:"Folder",category:"Context",description:"Resolve a real folder inside a canonical project.",defaults:{path:"."}},
 {type:"skill",title:"Skill",category:"Context",description:"Search trusted skill catalog with provenance.",defaults:{}},
 {type:"knowledge",title:"Knowledge",category:"Context",description:"Read project knowledge or memory.",defaults:{}},
 {type:"output",title:"Output",category:"Flow",description:"Collect workflow output.",defaults:{}},
];
export function workflowNodeCatalog(query=""){const q=query.trim().toLowerCase();return WORKFLOW_NODE_CATALOG.filter((item)=>!q||`${item.type} ${item.title} ${item.category} ${item.description}`.toLowerCase().includes(q));}
