import { parseWorkflowGraphDefinition } from "./graph-schema";
const edge=(id:string,source:string,target:string,sourceHandle?:string)=>({id,source,target,...(sourceHandle?{sourceHandle}:{})});
export const WORKFLOW_TEMPLATES=[
 {id:"scheduled-project-health",title:"Scheduled Project Health",description:"Resolve a project, inspect knowledge, then emit a receipt on a server schedule.",definition:parseWorkflowGraphDefinition({name:"Scheduled Project Health",description:"Generic server-side project health workflow.",status:"draft",inputs:{},metadata:{provenance:"template",tags:["schedule","project"]},nodes:[{id:"schedule",name:"Every Hour",type:"schedule",position:{x:60,y:120},config:{mode:"interval",everyMinutes:60}},{id:"project",name:"Project",type:"project",position:{x:320,y:120},config:{project:"PROJECT_ID"}},{id:"knowledge",name:"Knowledge",type:"knowledge",position:{x:580,y:120},config:{project:{"$ref":"nodes.project.output.id"}}},{id:"output",name:"Output",type:"output",position:{x:840,y:120},config:{}}],edges:[edge("e1","schedule","project"),edge("e2","project","knowledge"),edge("e3","knowledge","output")]} )},
 {id:"webhook-router",title:"Webhook Router",description:"Receive a webhook and route true/false before returning output.",definition:parseWorkflowGraphDefinition({name:"Webhook Router",description:"Generic webhook routing workflow.",status:"draft",inputs:{},metadata:{provenance:"template",tags:["webhook"]},nodes:[{id:"webhook",name:"Webhook",type:"webhook",position:{x:60,y:160},config:{methods:["POST"],responseMode:"lastNode"}},{id:"if",name:"Has Body",type:"condition",position:{x:320,y:160},config:{path:"input.body"}},{id:"yes",name:"Accepted",type:"output",position:{x:600,y:100},config:{value:{accepted:true}}},{id:"no",name:"Rejected",type:"output",position:{x:600,y:240},config:{value:{accepted:false}}}],edges:[edge("e1","webhook","if"),edge("e2","if","yes","true"),edge("e3","if","no","false")]} )},
 {id:"retry-action",title:"Retry Action",description:"Run one MSO tool with bounded retries and an error branch.",definition:parseWorkflowGraphDefinition({name:"Retry Action",description:"Generic retry/error handling starter.",status:"draft",inputs:{},metadata:{provenance:"template",tags:["retry","error"]},nodes:[{id:"manual",name:"Manual Trigger",type:"manual",position:{x:60,y:160},config:{}},{id:"action",name:"Action",type:"tool",position:{x:320,y:160},config:{tool:"PROJECT_TOOL",arguments:{},retry:{maxAttempts:3,backoffMs:1000}}},{id:"ok",name:"Success",type:"output",position:{x:600,y:100},config:{}},{id:"error",name:"Error",type:"output",position:{x:600,y:240},config:{value:{handled:true}}}],edges:[edge("e1","manual","action"),edge("e2","action","ok"),edge("e3","action","error","error")]} )},
] as const;
export function workflowTemplates(){return WORKFLOW_TEMPLATES.map(({id,title,description,definition})=>({id,title,description,tags:definition.metadata.tags??[],nodeCount:definition.nodes.length}));}
export function workflowTemplate(id:string){return WORKFLOW_TEMPLATES.find((row)=>row.id===id)??null;}
