"use client";
import { useEffect, useState } from "react";
import { Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Switch } from "@/components/ui/switch";
import { deleteVariable, listVariables, setVariable } from "../lib/api";
export function WorkflowVariablePanel(){const[rows,setRows]=useState<Awaited<ReturnType<typeof listVariables>>>([]),[key,setKey]=useState(""),[value,setValue]=useState(""),[secret,setSecret]=useState(false),[error,setError]=useState("");const load=async()=>setRows(await listVariables());useEffect(()=>{let cancelled=false;void listVariables().then((v)=>{if(!cancelled)setRows(v);}).catch((e)=>{if(!cancelled)setError(e instanceof Error?e.message:"Could not load variables");});return()=>{cancelled=true;};},[]);const save=async()=>{try{let parsed:unknown=value;try{parsed=JSON.parse(value);}catch{}await setVariable(key.toUpperCase(),parsed,secret);setKey("");setValue("");setSecret(false);await load();}catch(e){setError(e instanceof Error?e.message:"Save failed");}};return <ScrollArea className="h-full"><div className="space-y-3 p-3"><div><div className="text-xs font-semibold">Private variables</div><p className="mt-1 text-[10px] text-muted-foreground">Use {`{"$var":"KEY"}`} in node config. Secret values are never returned by the API.</p></div><Input placeholder="KEY" value={key} onChange={(e)=>setKey(e.target.value.toUpperCase())}/><Input type={secret?"password":"text"} placeholder="Value or JSON" value={value} onChange={(e)=>setValue(e.target.value)}/><label className="flex items-center justify-between text-xs"><span>Secret</span><Switch checked={secret} onCheckedChange={setSecret}/></label><Button size="sm" disabled={!key||!value} onClick={()=>void save()}>Save variable</Button>{error&&<p className="text-xs text-destructive">{error}</p>}<div className="space-y-1">{rows.map((row)=><div key={row.key} className="flex items-center justify-between rounded border p-2"><div><div className="text-xs font-medium">{row.key}</div><div className="text-[10px] text-muted-foreground">{row.secret?"secret":JSON.stringify(row.value)}</div></div><Button size="icon" variant="ghost" onClick={()=>void deleteVariable(row.key).then(load)}><Trash2 className="size-3"/></Button></div>)}</div></div></ScrollArea>;}
