"use client";
import { useMemo, useState } from "react";
import { ArrowLeftRight, Copy, FolderOpen, Trash2 } from "lucide-react";
import type { WorkflowGraph, WorkflowGraphNode, WorkflowGraphNodeType } from "@/lib/contracts/workflow-graph";
import { WORKFLOW_GRAPH_NODE_TYPES } from "@/lib/contracts/workflow-graph";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { openWindow } from "@/features/appshell";
import { resolveNode } from "../lib/api";
import { WorkflowAgentSeatField } from "./workflow-agent-seat-field";
import { WorkflowToolDirectoryField } from "./workflow-tool-directory-field";
import { WorkflowScriptField } from "./workflow-script-field";
const selectClass="h-9 w-full rounded-md border bg-background px-2";
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block space-y-1"><span className="text-muted-foreground">{label}</span>{children}</label>;}
function number(value:unknown,fallback:number){const n=Number(value);return Number.isFinite(n)?n:fallback;}

function AdvancedConfig({value,onApply}:{value:Record<string,unknown>;onApply:(text:string)=>void}){const[text,setText]=useState(JSON.stringify(value,null,2));return <Textarea className="min-h-40 font-mono text-[11px]" value={text} onChange={(e)=>setText(e.target.value)} onBlur={()=>onApply(text)}/>;}
function JsonField({label,value,onChange}:{label:string;value:unknown;onChange:(value:unknown)=>void}){const[text,setText]=useState(()=>JSON.stringify(value??{},null,2));return <Field label={label}><Textarea className="min-h-24 font-mono text-[11px]" value={text} onChange={(e)=>setText(e.target.value)} onBlur={()=>{try{onChange(JSON.parse(text));}catch{}}}/></Field>;}
export function WorkflowInspector({graph,graphs,node,onNode,onDeleteNode,onGraph}:{graph:WorkflowGraph;graphs:WorkflowGraph[];node:WorkflowGraphNode|null;onNode:(node:WorkflowGraphNode)=>void;onDeleteNode:(id:string)=>void;onGraph:(graph:WorkflowGraph)=>void;}){
 const[advancedError,setAdvancedError]=useState("");
 const outgoing=useMemo(()=>node?graph.edges.filter((edge)=>edge.source===node.id):[],[graph.edges,node]);
 if(!node){const tags=graph.metadata.tags?.join(", ")??"";return <div className="space-y-4 p-3 text-xs"><div className="font-semibold">Workflow settings</div><Field label="Description"><Textarea value={graph.description} onChange={(e)=>onGraph({...graph,description:e.target.value})}/></Field><Field label="Folder"><Input value={graph.metadata.folder??""} placeholder="Automation / Operations" onChange={(e)=>onGraph({...graph,metadata:{...graph.metadata,folder:e.target.value||undefined}})}/></Field><Field label="Tags"><Input value={tags} placeholder="deploy, qa, daily" onChange={(e)=>onGraph({...graph,metadata:{...graph.metadata,tags:e.target.value.split(",").map((v)=>v.trim()).filter(Boolean).slice(0,32)}})}/></Field><Field label="Timezone"><Input value={graph.metadata.timezone??"UTC"} placeholder="UTC" onChange={(e)=>onGraph({...graph,metadata:{...graph.metadata,timezone:e.target.value||undefined}})}/></Field><Field label="Error workflow"><select className={selectClass} value={graph.metadata.errorWorkflowId??""} onChange={(e)=>onGraph({...graph,metadata:{...graph.metadata,errorWorkflowId:e.target.value||undefined}})}><option value="">None</option>{graphs.filter((item)=>item.id!==graph.id).map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><p className="text-[10px] text-muted-foreground">Active schedule/webhook triggers execute server-side. Workflow data, versions, runs and variables stay private to the authenticated principal.</p></div>;}
 const projectValue=String(node.config.project??graph.metadata.project??"");
 const patch=(next:Partial<WorkflowGraphNode>)=>onNode({...node,...next}),setConfig=(key:string,value:unknown)=>patch({config:{...node.config,[key]:value}}),removeConfig=(key:string)=>{const next={...node.config};delete next[key];patch({config:next});};
 const patchEdge=(id:string,patch:Partial<WorkflowGraph["edges"][number]>)=>onGraph({...graph,edges:graph.edges.map((edge)=>edge.id===id?{...edge,...patch}:edge)});
 const reverseEdge=(id:string)=>onGraph({...graph,edges:graph.edges.map((edge)=>edge.id===id?{...edge,source:edge.target,target:edge.source,sourceHandle:undefined,targetHandle:undefined}:edge)});
 const applyAdvanced=(text:string)=>{try{const value=JSON.parse(text);if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Config must be an object");patch({config:value as Record<string,unknown>});setAdvancedError("");}catch(e){setAdvancedError(e instanceof Error?e.message:"Invalid JSON");}};
 const openTarget=async()=>{const resolved=await resolveNode(graph.id,node.id);openWindow("files-manager",resolved.name,undefined,{path:resolved.path},{multi:true});};
 const copyWebhook=()=>void navigator.clipboard?.writeText(`${window.location.origin}/api/v1/workflows/webhook/${graph.id}/${node.id}`);
 const actionNode=["tool","project_function","project_mcp","integration","script","agent","subflow","loop","repeat"].includes(node.type);
 return <div className="space-y-4 p-3 text-xs">
  <Field label="Name"><Input value={node.name} onChange={(e)=>patch({name:e.target.value})}/></Field>
  <Field label="Type"><select className={selectClass} value={node.type} onChange={(e)=>patch({type:e.target.value as WorkflowGraphNodeType})}>{WORKFLOW_GRAPH_NODE_TYPES.map((type)=><option key={type} value={type}>{type}</option>)}</select></Field>
  {node.type==="schedule"&&<><Field label="Schedule mode"><select className={selectClass} value={String(node.config.mode??"interval")} onChange={(e)=>setConfig("mode",e.target.value)}><option value="interval">Interval</option><option value="cron">Cron</option></select></Field>{node.config.mode==="cron"?<Field label="Cron (5 fields)"><Input value={String(node.config.cron??"0 * * * *")} onChange={(e)=>setConfig("cron",e.target.value)}/></Field>:<Field label="Every minutes"><Input type="number" min={1} max={10080} value={number(node.config.everyMinutes,60)} onChange={(e)=>setConfig("everyMinutes",Number(e.target.value))}/></Field>}<Field label="Timezone override"><Input value={String(node.config.timezone??"")} placeholder={graph.metadata.timezone??"UTC"} onChange={(e)=>setConfig("timezone",e.target.value)}/></Field></>}
  {node.type==="webhook"&&<><Field label="Methods"><Input value={Array.isArray(node.config.methods)?node.config.methods.join(", "):"POST"} onChange={(e)=>setConfig("methods",e.target.value.split(",").map((v)=>v.trim().toUpperCase()).filter(Boolean))}/></Field><Field label="Response"><select className={selectClass} value={String(node.config.responseMode??"onReceived")} onChange={(e)=>setConfig("responseMode",e.target.value)}><option value="onReceived">202 immediately</option><option value="lastNode">Wait for output</option></select></Field><Field label="Auth variable"><Input value={String(node.config.authVariable??"")} placeholder="WEBHOOK_TOKEN (optional)" onChange={(e)=>e.target.value?setConfig("authVariable",e.target.value.toUpperCase()):removeConfig("authVariable")}/></Field><div className="rounded border p-2"><div className="break-all font-mono text-[10px]">/api/v1/workflows/webhook/{graph.id}/{node.id}</div><Button className="mt-2" size="sm" variant="outline" onClick={copyWebhook}><Copy className="mr-1 size-3"/>Copy URL</Button></div></>}
  {node.type==="agent"&&<WorkflowAgentSeatField value={String(node.config.orgSeatId??"")} onChange={(value)=>value?setConfig("orgSeatId",value):removeConfig("orgSeatId")}/>}
  {(node.type==="project"||node.type==="folder"||node.type==="knowledge"||(node.type==="agent"&&!node.config.orgSeatId)||node.type==="script"||node.type==="project_function"||node.type==="project_mcp"||node.type==="subflow"||(node.type==="memory"&&node.config.scope==="project"))&&<Field label="Project"><Input value={String(node.config.project??graph.metadata.project??"")} placeholder="Canonical project id/name" onChange={(e)=>setConfig("project",e.target.value)}/></Field>}
  {node.type==="folder"&&<Field label="Relative path"><Input value={String(node.config.path??".")} onChange={(e)=>setConfig("path",e.target.value)}/></Field>}
  {node.type==="script"&&<WorkflowScriptField project={projectValue} value={String(node.config.script_id??"")} onChange={(value)=>value?setConfig("script_id",value):removeConfig("script_id")}/>}
  {node.type==="tool"&&<><WorkflowToolDirectoryField value={String(node.config.tool??"")} onChange={(value)=>setConfig("tool",value)}/><JsonField label="Arguments JSON" value={node.config.arguments??{}} onChange={(value)=>setConfig("arguments",value)}/></>}
  {node.type==="integration"&&<>{["user","provider","connection","operation"].map((key)=><Field key={key} label={key[0]!.toUpperCase()+key.slice(1)}><Input value={String(node.config[key]??"")} onChange={(e)=>setConfig(key,e.target.value)}/></Field>)}</>}
  {node.type==="agent"&&<Field label="Agent objective"><Textarea value={String(node.config.message??"")} onChange={(e)=>setConfig("message",e.target.value)}/></Field>}
  {node.type==="subflow"&&<><Field label="Workflow graph"><select className={selectClass} value={String(node.config.workflowId??"")} onChange={(e)=>e.target.value?setConfig("workflowId",e.target.value):removeConfig("workflowId")}><option value="">Legacy project flow</option>{graphs.filter((item)=>item.id!==graph.id).map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>{!node.config.workflowId&&<Field label="Legacy flow id"><Input value={String(node.config.flow??"")} onChange={(e)=>setConfig("flow",e.target.value)}/></Field>}</>}
  {node.type==="repeat"&&<><Field label="Workflow to repeat"><select className={selectClass} value={String(node.config.workflowId??"")} onChange={(e)=>e.target.value?setConfig("workflowId",e.target.value):removeConfig("workflowId")}><option value="">Select saved workflow</option>{graphs.filter((item)=>item.id!==graph.id).map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><JsonField label="Input JSON / bindings" value={node.config.input??{}} onChange={(value)=>setConfig("input",value)}/><Field label="Condition path"><Input value={String(node.config.path??"result.output")} placeholder="result.output.ok" onChange={(e)=>setConfig("path",e.target.value)}/></Field><label className="flex items-center justify-between"><span>Compare exact value</span><Switch checked={Object.hasOwn(node.config,"equals")} onCheckedChange={(checked)=>checked?setConfig("equals",true):removeConfig("equals")}/></label>{Object.hasOwn(node.config,"equals")&&<JsonField label="Expected JSON" value={node.config.equals} onChange={(value)=>setConfig("equals",value)}/>}<Field label="Max iterations"><Input type="number" min={1} max={50} value={number(node.config.maxIterations,5)} onChange={(e)=>setConfig("maxIterations",Number(e.target.value))}/></Field><Field label="Delay between iterations ms"><Input type="number" min={0} max={600000} value={number(node.config.delayMs,1000)} onChange={(e)=>setConfig("delayMs",Number(e.target.value))}/></Field><Field label="Max repeat duration ms"><Input type="number" min={1000} max={840000} value={number(node.config.maxDurationMs,600000)} onChange={(e)=>setConfig("maxDurationMs",Number(e.target.value))}/></Field><p className="text-[10px] text-muted-foreground">Each child run receives <code>input.repeat.iteration</code> and the previous iteration output. Route <code>done</code> when the condition matches or <code>exhausted</code> when limits are reached.</p></>}
  {node.type==="wait"&&<Field label="Delay ms"><Input type="number" min={0} max={600000} value={number(node.config.delayMs,1000)} onChange={(e)=>setConfig("delayMs",Number(e.target.value))}/></Field>}
  {node.type==="cache"&&<><Field label="Cache mode"><select className={selectClass} value={String(node.config.mode??"get_or_set")} onChange={(e)=>setConfig("mode",e.target.value)}>{["get_or_set","get","set","delete"].map((x)=><option key={x} value={x}>{x}</option>)}</select></Field><Field label="Cache key"><Input value={String(node.config.key??"")} onChange={(e)=>setConfig("key",e.target.value)}/></Field>{["get_or_set","set"].includes(String(node.config.mode??"get_or_set"))&&<><Field label="TTL seconds"><Input type="number" min={0} max={2592000} value={number(node.config.ttlSeconds,300)} onChange={(e)=>setConfig("ttlSeconds",Number(e.target.value))}/></Field><JsonField label="Value JSON / binding" value={node.config.value??{"$ref":"input"}} onChange={(value)=>setConfig("value",value)}/></>}</>}
  {node.type==="memory"&&<><Field label="Memory scope"><select className={selectClass} value={String(node.config.scope??"agent")} onChange={(e)=>setConfig("scope",e.target.value)}><option value="agent">Agent memory</option><option value="project">Project memory</option></select></Field><Field label="Memory mode"><select className={selectClass} value={String(node.config.mode??"search")} onChange={(e)=>setConfig("mode",e.target.value)}>{(node.config.scope==="project"?["search","remember"]:["read","search","remember","forget"]).map((x)=><option key={x} value={x}>{x}</option>)}</select></Field>{String(node.config.mode??"search")==="search"&&<Field label="Query"><Input value={String(node.config.query??"")} onChange={(e)=>setConfig("query",e.target.value)}/></Field>}{node.config.scope!=="project"&&<Field label="Document"><select className={selectClass} value={String(node.config.document??"MEMORY.md")} onChange={(e)=>setConfig("document",e.target.value)}><option value="MEMORY.md">MEMORY.md</option><option value="USER.md">USER.md</option></select></Field>}{["remember","forget"].includes(String(node.config.mode))&&<Field label="Memory key"><Input value={String(node.config.key??"")} onChange={(e)=>setConfig("key",e.target.value)}/></Field>}{String(node.config.mode)==="remember"&&<Field label={node.config.scope==="project"?"Summary":"Value"}><Textarea value={String(node.config.value??node.config.summary??"")} onChange={(e)=>setConfig(node.config.scope==="project"?"summary":"value",e.target.value)}/></Field>}</>}
  {node.type==="session"&&<><Field label="Session mode"><select className={selectClass} value={String(node.config.mode??"current")} onChange={(e)=>setConfig("mode",e.target.value)}>{["current","list","resume","note"].map((x)=><option key={x} value={x}>{x}</option>)}</select></Field>{node.config.mode==="resume"&&<Field label="Session label"><Input placeholder="agent-context-session" value={String(node.config.sessionRef??"")} onChange={(e)=>setConfig("sessionRef",e.target.value)}/></Field>}{node.config.mode==="note"&&<Field label="Note"><Textarea value={String(node.config.note??"")} onChange={(e)=>setConfig("note",e.target.value)}/></Field>}</>}
  {node.type==="directory"&&<><Field label="Directory source"><select className={selectClass} value={String(node.config.source??"tools")} onChange={(e)=>setConfig("source",e.target.value)}>{["tools","workflows","sessions","projects","skills"].map((x)=><option key={x} value={x}>{x}</option>)}</select></Field><Field label="Query"><Input value={String(node.config.query??"")} onChange={(e)=>setConfig("query",e.target.value)}/></Field><Field label="Limit"><Input type="number" min={1} max={100} value={number(node.config.limit,30)} onChange={(e)=>setConfig("limit",Number(e.target.value))}/></Field></>}
  {node.type==="batch"&&<><Field label="Items path"><Input value={String(node.config.itemsPath??"input.items")} onChange={(e)=>setConfig("itemsPath",e.target.value)}/></Field><Field label="Batch size"><Input type="number" min={1} max={1000} value={number(node.config.size,10)} onChange={(e)=>setConfig("size",Number(e.target.value))}/></Field></>}
  {node.type==="loop"&&<><Field label="Items path"><Input value={String(node.config.itemsPath??"input.items")} onChange={(e)=>setConfig("itemsPath",e.target.value)}/></Field><Field label="Tool per item"><Input value={String(node.config.tool??"")} onChange={(e)=>setConfig("tool",e.target.value)}/></Field><Field label="Concurrency"><Input type="number" min={1} max={4} value={number(node.config.concurrency,1)} onChange={(e)=>setConfig("concurrency",Number(e.target.value))}/></Field></>}
  {node.type==="merge"&&<Field label="Merge mode"><select className={selectClass} value={String(node.config.mode??"combine")} onChange={(e)=>setConfig("mode",e.target.value)}><option value="combine">Combine by source</option><option value="append">Append</option><option value="passThrough">Pass through latest</option></select></Field>}
  {actionNode&&<div className="space-y-3 rounded-lg border p-3"><div className="font-medium">Failure policy</div><Field label="Attempts"><Input type="number" min={1} max={5} value={number((node.config.retry as Record<string,unknown>|undefined)?.maxAttempts,1)} onChange={(e)=>setConfig("retry",{...((node.config.retry as Record<string,unknown>|undefined)??{}),maxAttempts:Number(e.target.value)})}/></Field><Field label="Backoff ms"><Input type="number" min={0} max={30000} value={number((node.config.retry as Record<string,unknown>|undefined)?.backoffMs,0)} onChange={(e)=>setConfig("retry",{...((node.config.retry as Record<string,unknown>|undefined)??{}),backoffMs:Number(e.target.value)})}/></Field><label className="flex items-center justify-between"><span>Continue on error</span><Switch checked={node.config.onError==="continue"} onCheckedChange={(checked)=>checked?setConfig("onError","continue"):removeConfig("onError")}/></label><p className="text-[10px] text-muted-foreground">Connect the red error port for an explicit error branch.</p></div>}
  {(node.type==="project"||node.type==="folder")&&<Button variant="secondary" size="sm" className="w-full" onClick={()=>void openTarget()}><FolderOpen className="mr-2 size-3"/>Open real folder</Button>}
  <details><summary className="cursor-pointer font-medium">Advanced config JSON</summary><div className="mt-2 space-y-2"><AdvancedConfig key={JSON.stringify(node.config)} value={node.config} onApply={applyAdvanced}/>{advancedError&&<p className="text-destructive">{advancedError}</p>}</div></details>
  <div className="space-y-2"><div className="font-medium">Connections</div>{outgoing.map((edge)=>{
    const target=graph.nodes.find((item)=>item.id===edge.target),reverseBlocked=["manual","schedule","webhook"].includes(node.type)||target?.type==="output";
    return <div key={edge.id} className="space-y-2 rounded border p-2"><div className="flex items-center gap-2"><span className="min-w-0 flex-1 truncate">{edge.sourceHandle?`${edge.sourceHandle} → `:"→ "}{target?.name??edge.target}</span><Button size="icon" variant="ghost" title="Reverse direction" aria-label={`Reverse ${node.name} to ${target?.name??edge.target}`} disabled={reverseBlocked} onClick={()=>reverseEdge(edge.id)}><ArrowLeftRight className="size-3"/></Button><Button size="icon" variant="ghost" aria-label={`Delete connection to ${target?.name??edge.target}`} onClick={()=>onGraph({...graph,edges:graph.edges.filter((item)=>item.id!==edge.id)})}><Trash2 className="size-3"/></Button></div><div className="grid grid-cols-[minmax(0,1fr)_auto] items-end gap-2"><Field label="Line style"><select className={selectClass} value={edge.style??"auto"} onChange={(e)=>patchEdge(edge.id,{style:e.target.value==="auto"?undefined:e.target.value as "solid"|"dashed"})}><option value="auto">Auto</option><option value="solid">Solid</option><option value="dashed">Dashed</option></select></Field><label className="flex h-9 items-center gap-2"><Switch checked={!edge.disabled} onCheckedChange={(checked)=>patchEdge(edge.id,{disabled:checked?undefined:true})}/><span>Active</span></label></div>{reverseBlocked?<p className="text-[9px] text-muted-foreground">Reverse is blocked when it would target a trigger or make Output a source.</p>:null}</div>;
  })}<p className="text-[10px] text-muted-foreground">Click an edge to focus its source node. Style is visual; Active controls execution/topology. Reverse swaps execution direction and is validated on save.</p></div>
  <Button variant="destructive" size="sm" className="w-full" onClick={()=>onDeleteNode(node.id)}><Trash2 className="mr-2 size-3"/>Delete node</Button>
 </div>;
}
