export const PROJECT_STATUS_URI = "ui://mso/project-status-v1.html";
export const DIFF_VIEW_URI = "ui://mso/project-diff-v1.html";
export const VPS_STATUS_URI = "ui://mso/vps-status-v1.html";

const ORIGIN = "https://mso.rahmanef.com";
const MIME = "text/html;profile=mcp-app";

function shell(title: string, body: string, script: string) {
  return String.raw`<main class="mso-card"><style>
:root{color-scheme:light dark;font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;background:transparent;color:CanvasText}.mso-card{padding:10px}.card{overflow:hidden;border:1px solid color-mix(in srgb,CanvasText 14%,transparent);border-radius:18px;background:color-mix(in srgb,Canvas 95%,transparent)}header{display:flex;align-items:center;gap:10px;padding:13px 14px;border-bottom:1px solid color-mix(in srgb,CanvasText 9%,transparent)}.mark{display:grid;place-items:center;width:30px;height:30px;border-radius:9px;background:color-mix(in srgb,#2563eb 16%,Canvas);font-weight:800}h2{margin:0;font-size:14px}.sub{margin:2px 0 0;color:color-mix(in srgb,CanvasText 58%,transparent);font-size:10px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1px;background:color-mix(in srgb,CanvasText 9%,transparent)}.cell{min-width:0;padding:10px 12px;background:Canvas}.cell span{display:block;font-size:9px;text-transform:uppercase;letter-spacing:.08em;color:color-mix(in srgb,CanvasText 52%,transparent)}.cell strong{display:block;margin-top:3px;font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.section{padding:10px 14px}.row{display:flex;align-items:center;justify-content:space-between;gap:10px;min-height:27px;border-top:1px solid color-mix(in srgb,CanvasText 8%,transparent);font-size:11px}.row:first-child{border-top:0}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.muted{color:color-mix(in srgb,CanvasText 52%,transparent)}.good{color:#16a34a}.bad{color:#dc2626}.files{margin:0;padding:0;list-style:none}.file{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;min-height:28px;align-items:center;border-top:1px solid color-mix(in srgb,CanvasText 8%,transparent);font-size:11px}.file:first-child{border-top:0}.file-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.actions{display:flex;justify-content:flex-end;gap:7px;padding:9px 12px;border-top:1px solid color-mix(in srgb,CanvasText 9%,transparent)}button{border:1px solid color-mix(in srgb,CanvasText 14%,transparent);background:color-mix(in srgb,CanvasText 5%,Canvas);color:CanvasText;border-radius:10px;padding:7px 10px;font:inherit;font-size:11px;cursor:pointer}@media(max-width:440px){.mso-card{padding:6px}.grid{grid-template-columns:1fr 1fr}.wide{grid-column:1/-1}}
</style><section class="card"><header><div class="mark">M</div><div><h2>${title}</h2><p class="sub" id="subtitle">MSO</p></div></header>${body}<div class="actions"><button id="refresh" hidden>Refresh</button><button id="open">Open MSO ↗</button></div></section><script>${script}</script></main>`;
}

const sharedScript = String.raw`
const MSO_URL="https://mso.rahmanef.com";const $=id=>document.getElementById(id);let last=null;
const txt=(v,f="—")=>v===undefined||v===null||v===""?f:String(v);const esc=v=>txt(v);
function output(){return window.openai&&window.openai.toolOutput?window.openai.toolOutput:null}
async function openMso(){if(window.openai&&typeof window.openai.openExternal==="function")await window.openai.openExternal({href:MSO_URL,redirectUrl:false});else window.open(MSO_URL,"_blank","noopener,noreferrer")}
$("open").addEventListener("click",openMso);window.addEventListener("openai:set_globals",()=>{const v=output();if(v)render(v)},{passive:true});window.addEventListener("message",e=>{if(e.source!==window.parent)return;const m=e.data;if(m&&m.method==="ui/notifications/tool-result"&&m.params&&m.params.structuredContent)render(m.params.structuredContent)},{passive:true});
`;

const projectBody = String.raw`<div class="grid"><div class="cell wide"><span>Project</span><strong id="project">—</strong></div><div class="cell"><span>Branch</span><strong id="branch">—</strong></div><div class="cell"><span>HEAD</span><strong class="mono" id="head">—</strong></div><div class="cell"><span>Working tree</span><strong id="clean">—</strong></div></div><div class="section"><div class="row"><span>Package</span><strong id="package">—</strong></div><div class="row"><span>Database</span><strong id="database">—</strong></div><div class="row"><span>Project MCP</span><strong id="mcp">0</strong></div><div class="row"><span>Knowledge</span><strong id="knowledge">—</strong></div></div>`;
const projectScript = sharedScript + String.raw`
let projectId="";function render(v){last=v||{};const p=v.project||{},g=v.git||{},pkg=v.package||{},db=v.database||{},i=v.integrations||{},k=v.knowledge||{};projectId=txt(p.id,"");$("project").textContent=txt(p.name);$("subtitle").textContent=txt(p.path,"Project status");$("branch").textContent=txt(g.branch);$("head").textContent=g.head&&g.head.sha?String(g.head.sha).slice(0,12):"—";$("clean").textContent=g.clean===true?"Clean":g.clean===false?(String(Array.isArray(g.changes)?g.changes.length:0)+" change(s)"):"Unknown";$("clean").className=g.clean===true?"good":g.clean===false?"bad":"";$("package").textContent=[pkg.name,pkg.version].filter(Boolean).join(" · ")||"—";$("database").textContent=db.detected?("Convex · "+txt(db.mode)):"Not detected";$("mcp").textContent=String(Array.isArray(i.projectMcp)?i.projectMcp.length:0);$("knowledge").textContent=k.exists?(txt(k.bytes,0)+" bytes"):"Not set";$("refresh").hidden=!projectId}
$("refresh").addEventListener("click",async()=>{if(!projectId||!window.openai||typeof window.openai.callTool!=="function")return;const r=await window.openai.callTool("project_get",{project:projectId});render(r&&r.structuredContent?r.structuredContent:r)});const initial=output();if(initial)render(initial);
`;

const diffBody = String.raw`<div class="grid"><div class="cell wide"><span>Project</span><strong id="project">—</strong></div><div class="cell"><span>Mode</span><strong id="mode">—</strong></div><div class="cell"><span>Files</span><strong id="count">0</strong></div><div class="cell"><span>Lines</span><strong id="lines">+0 −0</strong></div></div><div class="section"><ul class="files" id="files"></ul><div class="muted" id="empty">No changed files.</div></div>`;
const diffScript = sharedScript + String.raw`
function render(v){last=v||{};const p=v.project||{},s=v.summary||{},files=Array.isArray(v.files)?v.files:[];$("project").textContent=txt(p.name);$("subtitle").textContent=v.sha?("Commit "+String(v.sha).slice(0,12)):"Current changes";$("mode").textContent=txt(v.mode);$("count").textContent=txt(s.files,files.length);$("lines").textContent="+"+txt(s.additions,0)+" −"+txt(s.deletions,0);const ul=$("files");ul.textContent="";$("empty").hidden=files.length>0;for(const f of files.slice(0,80)){const li=document.createElement("li");li.className="file";const n=document.createElement("span");n.className="file-name mono";n.textContent=txt(f.file);const d=document.createElement("span");d.className="muted";d.textContent="+"+txt(f.added,"?")+" −"+txt(f.deleted,"?");li.append(n,d);ul.append(li)}}const initial=output();if(initial)render(initial);
`;

const vpsBody = String.raw`<div class="grid"><div class="cell"><span>Load</span><strong id="load">—</strong></div><div class="cell"><span>Memory</span><strong id="memory">—</strong></div><div class="cell"><span>Disk</span><strong id="disk">—</strong></div></div><div class="section"><div class="row"><span>Uptime</span><strong id="uptime">—</strong></div><div class="row"><span>Managed apps</span><strong id="apps">—</strong></div><div class="row"><span>Browser</span><strong id="browser">—</strong></div><div class="row"><span>Infrastructure</span><strong id="infra">—</strong></div></div>`;
const vpsScript = sharedScript + String.raw`
const pct=n=>Number.isFinite(Number(n))?(String(Math.round(Number(n)))+"%"):"—";function render(v){last=v||{};const h=v.health||{},a=Array.isArray(v.apps)?v.apps:[],b=v.browser||{},infra=Array.isArray(v.infrastructure)?v.infrastructure:[];$("subtitle").textContent="Live bounded VPS overview";const load=h.load||h.cpu||{};$("load").textContent=Array.isArray(load)?load.map(x=>Number(x).toFixed(2)).join(" / "):txt(load.one||load.load1||h.load1);const mem=h.memory||{};$("memory").textContent=mem.percentUsed!==undefined?pct(mem.percentUsed):mem.used&&mem.total?pct(mem.used/mem.total*100):"—";const disk=h.disk||{};$("disk").textContent=disk.percentUsed!==undefined?pct(disk.percentUsed):disk.used&&disk.total?pct(disk.used/disk.total*100):"—";$("uptime").textContent=h.uptimeSeconds!==undefined?(String(Math.round(Number(h.uptimeSeconds)/3600))+"h"):"—";$("apps").textContent=String(a.filter(x=>x.running).length)+"/"+String(a.length)+" running";$("browser").textContent=b.running?"Running":b.installed?"Stopped":"Not installed";$("infra").textContent=String(infra.filter(x=>x.configured).length)+"/"+String(infra.length)+" configured";$("refresh").hidden=false}
$("refresh").addEventListener("click",async()=>{if(!window.openai||typeof window.openai.callTool!=="function")return;const r=await window.openai.callTool("vps_status",{});render(r&&r.structuredContent?r.structuredContent:r)});const initial=output();if(initial)render(initial);
`;

function meta(description: string) {
  return {
    ui: { prefersBorder: true, csp: { connectDomains: [], resourceDomains: [] } },
    "openai/widgetDescription": description,
    "openai/widgetPrefersBorder": true,
    "openai/widgetCSP": { connect_domains: [], resource_domains: [], redirect_domains: [ORIGIN] },
  };
}

export const OPERATOR_UI_RESOURCES = [
  { uri: PROJECT_STATUS_URI, name: "MSO project status", description: "Interactive project snapshot.", mimeType: MIME, text: shell("MSO project", projectBody, projectScript), _meta: meta("MSO project status card with bounded Git, Convex, knowledge and integration state.") },
  { uri: DIFF_VIEW_URI, name: "MSO project diff", description: "Compact project diff summary.", mimeType: MIME, text: shell("MSO diff", diffBody, diffScript), _meta: meta("MSO project diff summary. Raw diff text remains in the tool fallback and is not injected as HTML.") },
  { uri: VPS_STATUS_URI, name: "MSO VPS status", description: "Interactive bounded VPS overview.", mimeType: MIME, text: shell("MSO VPS", vpsBody, vpsScript), _meta: meta("MSO live bounded VPS overview for health, managed apps, browser and infrastructure readiness.") },
] as const;
