import { GOOGLE_CONNECTION_UI_SCRIPT } from "./google-connection-ui";
import { PROJECT_MCP_UI_SCRIPT } from "./project-mcp-ui";
export { CONNECTION_MANAGER_STYLE } from "./connection-ui-style";
import { PROVIDER_ICON_PATHS } from "./provider-icons";
export const CONNECTION_MANAGER_SCRIPT=GOOGLE_CONNECTION_UI_SCRIPT+PROJECT_MCP_UI_SCRIPT+`const PROVIDER_ICON_PATHS=${JSON.stringify(PROVIDER_ICON_PATHS)};`+String.raw`
function mountConnectionManager(root,catalog,bridge,initial={}){
  let disposed=false,sequence=0,snapshot=initial.snapshot||{users:[],connections:[],bindings:[]},user=initial.user||snapshot.user||null,provider=catalog.find(p=>p.id===initial.provider)||catalog.find(p=>p.id==="github")||catalog[0];
  let detail,status,container,sidebarPanel,sidebarBackdrop,sidebarToggle,navButtons=[],navMode=["variables","ai-providers"].includes(initial.section)?initial.section:"provider",sidebarOpen=false;
  const ready=c=>c.state==="verified"||c.state==="ACTIVE";
  const stateLabel=c=>({"app-configured":"App configured · consent required","app-required":"OAuth app required","authorization-pending":"Consent pending","authorization-required":"Consent required","reauthorization-required":"Reconnect required","scope-missing":"Permission missing","authorized":"Authorized · verify access"}[c.state])||(ready(c)?"Verified":c.state==="incomplete"?"Needs setup":c.state==="configured"?"Not verified":c.state==="invalid"?"Access rejected":c.state==="unavailable"?"Check unavailable":c.state==="unconfigured"?"Needs setup":"Authorize");
  const mark=p=>{const wrap=n("span",undefined,"provider-mark"),svg=document.createElementNS("http://www.w3.org/2000/svg","svg"),shape=document.createElementNS("http://www.w3.org/2000/svg","path");wrap.setAttribute("aria-hidden","true");svg.setAttribute("viewBox","0 0 24 24");shape.setAttribute("d",PROVIDER_ICON_PATHS[p.id]||"M8 2h8v5h5v10h-5v5H8v-5H3V7h5V2zm2 2v5H5v6h5v5h4v-5h5V9h-5V4z");svg.append(shape);wrap.append(svg);return wrap};
  const human=s=>s.replaceAll("-"," ").replaceAll("_"," ");
  const n=(tag,text,cls)=>{const v=integrationNode(tag,text);if(cls)v.className=cls;return v};
  const b=(text,fn,cls)=>{const v=n("button",text,cls);v.type="button";v.addEventListener("click",fn);return v};
  const input=(label,value="",type="text")=>{const l=n("label",label),i=n("input");i.type=type;i.value=value;i.autocomplete="off";i.maxLength=120;l.append(i);return{label:l,input:i}};
  const choicePicker=(label,rows,selected,onChoose)=>{
    const wrap=n("div",undefined,"owner-picker"),caption=n("span",label,"identity-picker-label"),trigger=b("",()=>{popup.hidden?open():close()},"owner-picker-trigger"),popup=n("div",undefined,"owner-picker-popup");let value=selected||"";const options=[];
    wrap.setAttribute("role","group");wrap.setAttribute("aria-label",label);trigger.setAttribute("aria-haspopup","listbox");trigger.setAttribute("aria-expanded","false");popup.hidden=true;popup.setAttribute("role","listbox");popup.setAttribute("aria-label",label+" options");
    const current=()=>rows.find(row=>row.id===value),paint=()=>{const row=current();trigger.textContent=row?row.text:"Choose "+label.toLowerCase();for(const pair of options)pair[1].setAttribute("aria-selected",String(pair[0].id===value))};
    const close=(focus=false)=>{popup.hidden=true;trigger.setAttribute("aria-expanded","false");if(focus)trigger.focus()},open=()=>{popup.hidden=false;trigger.setAttribute("aria-expanded","true");const pair=options.find(pair=>pair[0].id===value)||options[0];pair?.[1].focus()},pick=row=>{value=row.id;paint();close(true);onChoose(row)};
    for(const row of rows){const option=b(row.text,()=>pick(row),"owner-picker-option");option.setAttribute("role","option");option.tabIndex=-1;options.push([row,option]);popup.append(option)}
    const move=(event,delta)=>{event.preventDefault();if(popup.hidden){open();return}const active=options.findIndex(pair=>pair[1]===document.activeElement),next=(active<0?(delta>0?0:options.length-1):(active+delta+options.length)%options.length);options[next]?.[1].focus()};
    trigger.addEventListener("keydown",event=>{if(event.key==="ArrowDown")move(event,1);else if(event.key==="ArrowUp")move(event,-1);else if(event.key==="Escape"){event.preventDefault();close()}});
    popup.addEventListener("keydown",event=>{if(event.key==="ArrowDown")move(event,1);else if(event.key==="ArrowUp")move(event,-1);else if(event.key==="Home"){event.preventDefault();options[0]?.[1].focus()}else if(event.key==="End"){event.preventDefault();options.at(-1)?.[1].focus()}else if(event.key==="Escape"){event.preventDefault();close(true)}});
    wrap.addEventListener("focusout",()=>setTimeout(()=>{if(!wrap.contains(document.activeElement))close()},0));wrap.append(caption,trigger,popup);paint();return{wrap,get value(){return value},set value(next){value=next;paint()}};
  };
  const textError=e=>({user_required:"Select a credential owner first.",connection_ambiguous:"Choose a named connection; more than one account exists.",connection_has_folder_binding:"Remove or change this connection's folder binding before deleting it.",integration_has_variables:"Remove Integration Variables that point to this owner or connection first.",invalid_variable_key:"Variable names use uppercase A-Z, 0-9 and underscore.",connection_busy:"This connection is being used. Retry after that operation finishes.",choose_auth_config_id:"Several Composio auth configs match. Enter the intended auth config ID.",matching_auth_config_required:"Select a matching Composio auth config, or explicitly permit managed OAuth setup.",composio_project_key_required:"Configure a Composio project key under this same credential owner first.",external_source_requires_own_executor:"This connection uses an external backend; a local API key will not be substituted.",user_has_shared_dependents:"Unshare this owner’s shared connections before deleting the owner.",connection_has_shared_dependents:"Unshare dependent accounts before deleting this connection.",shared_alias_readonly:"Shared connections are read-only. Rotate credentials from the owner connection.",shared_alias_cannot_share:"A shared connection cannot be shared again. Share from its owner instead.",external_connections_cannot_share:"Only direct MSO credentials can be shared between credential owners.",shared_alias_use_unshare:"Use Unshare to remove a shared connection without touching its owner.",owner_required:"Sign in as an Owner before changing connections."}[e.code||e.message]||e.message||"Operation failed.");
  function remember(){if(bridge.remember)bridge.remember({user,provider:provider.id})}
  async function reload(){const version=++sequence;if(!bridge.query){draw();return}try{const next=await bridge.query({view:"snapshot",...(user?{user}:{})});if(disposed||version!==sequence)return;snapshot=next;user=next.user||user;draw();remember()}catch(e){if(!disposed){draw();status.textContent=textError(e)}}}
  async function change(args,after=reload){if(!bridge.manage)return;try{status.textContent="Saving connection metadata…";await bridge.manage({...args,confirm:true});await after()}catch(e){status.textContent=textError(e)}}
  function guide(method,parent=detail){const d=n("details",undefined,"identity-guide");d.open=parent!==detail;d.append(n("summary","How to get this credential / authorization"));const g=method.guidance,ol=n("ol");for(const step of g.steps)ol.append(n("li",step));d.append(ol);for(const[url,label]of [[g.url,"Official setup page"],[g.reference,"Documentation"]]){const a=n("a",label);a.href=url;a.rel="noopener noreferrer";a.target="_blank";if(bridge.openLink)a.addEventListener("click",e=>{e.preventDefault();Promise.resolve(bridge.openLink(url)).catch(error=>status.textContent=textError(error))});d.append(a)}parent.append(d)}
  function setSidebar(open){const wasOpen=sidebarOpen;sidebarOpen=Boolean(open);if(sidebarPanel)sidebarPanel.dataset.open=String(sidebarOpen);if(sidebarBackdrop)sidebarBackdrop.hidden=!sidebarOpen;if(sidebarToggle)sidebarToggle.setAttribute("aria-expanded",String(sidebarOpen));if(sidebarOpen)setTimeout(()=>sidebarPanel?.querySelector("input,button")?.focus(),0);else if(wasOpen&&sidebarToggle)setTimeout(()=>sidebarToggle.focus(),0)}
  function activateNav(mode){navMode=mode;for(const entry of navButtons){const on=entry.mode===mode&&(mode!=="provider"||entry.provider===provider.id);entry.button.setAttribute("aria-current",on?"page":"false");entry.button.setAttribute("aria-pressed",String(on))}}
  function showProfiles(){navMode="owners";activateNav(navMode);setSidebar(false);profiles()}
  function showBindings(){navMode="routing";activateNav(navMode);setSidebar(false);bindings()}
  function showTransfer(){navMode="transfer";activateNav(navMode);setSidebar(false);if(bridge.mountTransfer)bridge.mountTransfer(detail,()=>{navMode="provider";activateNav(navMode);drawProvider()});else if(bridge.openTransfer)bridge.openTransfer();else bridge.openTransferBrowser?.()}
  function showProjectMcp(){navMode="project-mcp";activateNav(navMode);setSidebar(false);mountProjectMcpForm(detail,bridge,snapshot,user,status,()=>{navMode="provider";activateNav(navMode);drawProvider()},{n,b,input})}
  function showVariables(){navMode="variables";activateNav(navMode);setSidebar(false);variables()}
  function showAiProviders(){navMode="ai-providers";activateNav(navMode);setSidebar(false);void aiProviders()}
  function selectProvider(p){provider=p;navMode="provider";remember();activateNav(navMode);setSidebar(false);drawProvider()}
  function draw(){
    root.replaceChildren();root.classList.add("integration","manager");
    const shell=n("div",undefined,"integration-settings-shell");
    sidebarBackdrop=b("",()=>setSidebar(false),"integration-sidebar-backdrop");sidebarBackdrop.hidden=true;sidebarBackdrop.setAttribute("aria-label","Close Integrations sections");
    sidebarPanel=n("aside",undefined,"integration-settings-sidebar");sidebarPanel.id="integration-settings-sidebar";sidebarPanel.dataset.open="false";
    const sidebarHeader=n("div",undefined,"integration-sidebar-header"),brand=n("div",undefined,"integration-sidebar-brand"),brandIcon=n("span","M","integration-brand-icon"),brandCopy=n("span");brandCopy.append(n("strong","MSO"),n("small","Integrations"));brand.append(brandIcon,brandCopy);
    const search=n("input");search.type="search";search.placeholder="Search";search.setAttribute("aria-label","Search integrations");
    const owner=choicePicker("Credential owner",snapshot.users.map(row=>({id:row.id,text:row.label+" · "+row.id+(row.isDefault?" · default":"")})),user,row=>{user=row.id;remember();void reload()});
    sidebarHeader.append(brand,search,owner.wrap);sidebarPanel.append(sidebarHeader);sidebarPanel.addEventListener("keydown",event=>{if(event.key==="Escape"&&sidebarOpen){event.preventDefault();setSidebar(false)}});
    const nav=n("nav",undefined,"integration-settings-nav");nav.setAttribute("aria-label","Integrations sections");
    const connectionGroup=n("div",undefined,"integration-nav-group"),connectionLabel=n("p","Connections","integration-nav-label");connectionGroup.append(connectionLabel);
    navButtons=[];for(const p of catalog){const item=b(undefined,()=>selectProvider(p),"integration-nav-item");item.append(mark(p),n("span",p.title));const count=snapshot.connections.filter(c=>c.provider===p.id).length;if(count){const badge=n("span",String(count),"provider-count");badge.setAttribute("aria-hidden","true");item.append(badge)}navButtons.push({mode:"provider",provider:p.id,button:item});connectionGroup.append(item)}
    const manageGroup=n("div",undefined,"integration-nav-group"),manageLabel=n("p","Manage","integration-nav-label");manageGroup.append(manageLabel);
    const management=[
      ["owners","Credential owners",showProfiles],
      ["ai-providers","AI Providers",showAiProviders],
      ["variables","Variables",showVariables],
      ["routing","Project routing",showBindings],
      ["transfer","Transfer & backup",showTransfer],
      ["project-mcp","Add project MCP",showProjectMcp],
    ];
    for(const [mode,label,fn] of management){const item=b(label,fn,"integration-nav-item integration-nav-utility");if((mode==="owners"||mode==="routing")&&!bridge.manage)item.disabled=true;if(mode==="transfer"&&!bridge.openTransfer&&!bridge.openTransferBrowser)item.disabled=true;if(mode==="project-mcp"&&!bridge.projectMcp)item.disabled=true;navButtons.push({mode,provider:null,button:item});manageGroup.append(item)}
    nav.append(connectionGroup,manageGroup);sidebarPanel.append(nav);
    const sidebarFooter=n("div",undefined,"integration-sidebar-footer"),refresh=b("Refresh",reload);sidebarFooter.append(refresh);sidebarPanel.append(sidebarFooter);
    search.addEventListener("input",()=>{const q=search.value.trim().toLowerCase();for(const entry of navButtons){if(entry.mode!=="provider")continue;const p=catalog.find(row=>row.id===entry.provider);entry.button.hidden=Boolean(q)&&!(p.title+" "+p.id).toLowerCase().includes(q)}});

    const content=n("main",undefined,"integration-settings-content"),mobileBar=n("div",undefined,"integration-mobile-toolbar");sidebarToggle=b("Integrations sections",()=>setSidebar(true),"integration-sidebar-toggle");sidebarToggle.setAttribute("aria-controls","integration-settings-sidebar");sidebarToggle.setAttribute("aria-expanded","false");mobileBar.append(sidebarToggle);content.append(mobileBar);
    if(!bridge.manage)content.append(n("p","Sign in as an MSO Owner to manage credentials. Device roles and credential users are different; public setup guides remain available.","identity-readonly"));
    detail=n("section",undefined,"identity-detail integration-settings-detail");status=n("p",undefined,"identity-feedback");status.setAttribute("role","status");status.setAttribute("aria-live","polite");content.append(detail,status);
    shell.append(sidebarPanel,sidebarBackdrop,content);root.append(shell);container=shell;
    activateNav(navMode);
    if(navMode==="owners")profiles();else if(navMode==="variables")variables();else if(navMode==="ai-providers")void aiProviders();else if(navMode==="routing")bindings();else if(navMode==="project-mcp")showProjectMcp();else drawProvider();
  }
  function confirmation(title,id,fn){detail.replaceChildren(n("h2",title),n("p","This changes only the selected identity. Type “"+id+"” to confirm."));const value=input("Confirmation");detail.append(value.label,b("Confirm",()=>{if(value.input.value!==id){status.textContent="Confirmation does not match.";return}void fn()},"danger"),b("Cancel",()=>{navMode="provider";activateNav(navMode);drawProvider()}));}
  function profiles(){
    detail.replaceChildren(n("h2","Credential owners"),n("p","These profiles isolate service accounts. They do not grant MSO device roles."));
    const id=input("New user ID"),name=input("Display label");detail.append(id.label,name.label);const create=b("Create user",()=>change({action:"user.create",user:id.input.value,label:name.input.value||id.input.value},async()=>{user=id.input.value;await reload()}),"primary");create.disabled=!bridge.manage;detail.append(create);
    if(!user)return;const current=snapshot.users.find(u=>u.id===user);detail.append(n("h3",current?.label||user));
    const target=input("Target user ID"),label=input("New display label",current?.label||user),copy=input("", "","checkbox");copy.input.checked=false;copy.label.className="identity-check";copy.label.append(document.createTextNode("Copy saved direct credentials when duplicating (otherwise metadata only)"));
    detail.append(target.label,label.label,copy.label);const row=n("div",undefined,"identity-actions");
    for(const[text,action]of [["Rename user","user.rename"],["Duplicate user","user.duplicate"]]){const button=b(text,()=>change({action,user,target:target.input.value,label:label.input.value,...(action==="user.duplicate"?{copyCredentials:copy.input.checked}:{})},async()=>{user=target.input.value;await reload()}));button.disabled=!bridge.manage;row.append(button)}
    const def=b("Set default user",()=>change({action:"user.default",user}));def.disabled=!bridge.manage;row.append(def);const del=b("Delete user",()=>confirmation("Delete credential owner",user,()=>change({action:"user.delete",user},async()=>{user=null;await reload()})),"danger");del.disabled=!bridge.manage;row.append(del);detail.append(row);
  }
  function bindings(){
    detail.replaceChildren(n("h2","Folder → credential context"),n("p","The longest matching folder selects its credential user and optional provider connection. It never changes another user's defaults."));
    const folder=input("Absolute project folder"),connection=input("Connection ID (optional)");detail.append(folder.label,connection.label);const save=b("Bind this folder",()=>change({action:"folder.map",path:folder.input.value,user,...(connection.input.value?{provider:provider.id,connection:connection.input.value}:{})}));save.disabled=!user||!bridge.manage;detail.append(save);
    for(const binding of snapshot.bindings){const card=n("div",undefined,"connection-card");card.append(n("strong",binding.path),n("p",binding.user+" · "+Object.entries(binding.connections).map(([p,id])=>p+"="+id).join(", ")));const remove=b("Remove binding",()=>change({action:"folder.unmap",path:binding.path}));remove.disabled=!bridge.manage;card.append(remove);detail.append(card)}
  }
  function variables(){
    detail.replaceChildren(n("h2","Integration Variables"),n("p","Metadata-only aliases point to named Integrations connections. Credentials are never copied into a variable."));
    const variables=snapshot.variables&&typeof snapshot.variables==="object"?snapshot.variables:{};
    const entries=Object.entries(variables).sort(([a],[b])=>a.localeCompare(b));
    if(!entries.length)detail.append(n("p","No Integration Variables yet.","identity-muted"));
    for(const[key,ref]of entries){const card=n("article",undefined,"connection-card"),top=n("header",undefined,"connection-heading"),copy=n("div");copy.append(n("h3",key),n("small",ref.user+" / "+ref.provider+" / "+ref.connection));top.append(copy);card.append(top);if(key==="JEV")card.append(n("p","Default decision-kernel alias used by Workflow Optimizer.","identity-muted"));const remove=b("Remove",()=>change({action:"variable.delete",key}),"danger");remove.disabled=!bridge.manage;card.append(n("div",undefined,"identity-actions"));card.lastChild.append(remove);detail.append(card)}
    const editor=n("div",undefined,"connection-card");editor.append(n("h3","Add or update variable"),n("p","Select a credential owner in the sidebar, then point the variable to one of that owner’s named connections.","identity-muted"));
    if(!user){editor.append(n("p","Select a credential owner first.","identity-muted"));detail.append(editor);return}
    const key=input("Variable name",variables.JEV?"":"JEV"),providerSelect=n("select"),providerLabel=n("label","Provider"),connectionSelect=n("select"),connectionLabel=n("label","Named connection");
    providerLabel.append(providerSelect);connectionLabel.append(connectionSelect);
    for(const p of catalog){const o=n("option",p.title);o.value=p.id;providerSelect.append(o)}
    providerSelect.value=catalog.some(p=>p.id==="mcp")?"mcp":provider.id;
    const fillConnections=()=>{connectionSelect.replaceChildren();const rows=snapshot.connections.filter(c=>c.provider===providerSelect.value);for(const c of rows){const o=n("option",c.label+" · "+c.id);o.value=c.id;connectionSelect.append(o)}};
    providerSelect.addEventListener("change",fillConnections);fillConnections();key.input.addEventListener("input",()=>key.input.value=key.input.value.toUpperCase().replace(/[^A-Z0-9_]/g,"").slice(0,64));
    const fields=n("div",undefined,"identity-fields");fields.append(key.label,providerLabel,connectionLabel);editor.append(fields);
    const save=b("Save variable",()=>{if(!key.input.value||!connectionSelect.value){status.textContent="Choose a variable name and named connection.";return}void change({action:"variable.set",key:key.input.value,user,provider:providerSelect.value,connection:connectionSelect.value})},"primary");save.disabled=!bridge.manage;editor.append(save);detail.append(editor);
  }
  async function aiProviders(){
    detail.replaceChildren(n("h2","AI Providers"),n("p","Configure Alfa’s active model provider here. This view uses the same AI runtime/config store as Settings; it does not create another credential registry."));
    if(!bridge.aiConfig||!bridge.aiCatalog||!bridge.aiModels||!bridge.aiSave){
      const card=n("div",undefined,"identity-empty");card.append(n("h3","Open native MSO"),n("p","AI provider credentials are managed only in the private native MSO page, not through the MCP Page payload."));
      if(bridge.openAiProviders)card.append(b("Open AI Providers",()=>bridge.openAiProviders(),"primary"));detail.append(card);return;
    }
    const loading=n("p","Loading AI providers…","identity-muted");detail.append(loading);
    try{
      const[cfg,catalogResult]=await Promise.all([bridge.aiConfig(),bridge.aiCatalog()]);if(navMode!=="ai-providers")return;
      const dynamic=Array.isArray(catalogResult?.providers)?catalogResult.providers:[],connected=Array.isArray(cfg?.providers)?cfg.providers:[],meta=new Map();
      for(const row of dynamic)meta.set(row.id,{id:row.id,name:row.name||row.id,...row});for(const row of connected)meta.set(row.id,{id:row.id,name:meta.get(row.id)?.name||row.id,...meta.get(row.id),...row});if(cfg.provider&&!meta.has(cfg.provider))meta.set(cfg.provider,{id:cfg.provider,name:cfg.provider});
      detail.replaceChildren(n("h2","AI Providers"),n("p","Alfa provider/model selection and credentials share the exact Settings SSOT. Saved keys stay server-side and are only shown masked."));
      const providerSelect=n("select"),providerLabel=n("label","Active provider"),modelSelect=n("select"),modelLabel=n("label","Model"),key=input("API key","","password"),fields=n("div",undefined,"identity-fields");
      for(const row of [...meta.values()].sort((a,b)=>String(a.name).localeCompare(String(b.name)))){const o=n("option",row.name+(row.freeAgentModelCount? " · "+row.freeAgentModelCount+" free agent model"+(row.freeAgentModelCount===1?"":"s"):""));o.value=row.id;providerSelect.append(o)}
      providerSelect.value=cfg.provider||providerSelect.options[0]?.value||"";providerLabel.append(providerSelect);modelLabel.append(modelSelect);fields.append(providerLabel,modelLabel,key.label);detail.append(fields);
      const currentMeta=()=>connected.find(row=>row.id===providerSelect.value),syncKey=()=>{const row=currentMeta();key.label.hidden=row?.kind==="oauth";key.input.value="";key.input.placeholder=row?.masked||"API key (leave blank to keep existing)";};
      const loadModels=async()=>{modelSelect.replaceChildren();modelSelect.disabled=true;try{const result=await bridge.aiModels(providerSelect.value),rows=Array.isArray(result?.models)?result.models:[];const connectedModels=currentMeta()?.models||[],ids=[...new Set([...connectedModels,...rows.map(row=>row.id)].filter(Boolean))];if(providerSelect.value===cfg.provider&&cfg.model&&!ids.includes(cfg.model))ids.unshift(cfg.model);for(const id of ids){const row=rows.find(x=>x.id===id),o=n("option",(row?.free?"Free · ":"")+String(row?.name||id));o.value=id;modelSelect.append(o)}if(providerSelect.value===cfg.provider&&cfg.model)modelSelect.value=cfg.model;else if(ids.length)modelSelect.value=ids[0]}catch(e){status.textContent=textError(e)}finally{modelSelect.disabled=false}};
      providerSelect.addEventListener("change",()=>{syncKey();void loadModels()});syncKey();await loadModels();
      const save=async(test=false)=>{try{status.textContent=test?"Saving before test…":"Saving AI provider…";await bridge.aiSave({provider:providerSelect.value,...(modelSelect.value?{model:modelSelect.value}:{}),...(key.input.value.trim()?{apiKey:key.input.value.trim()}:{})});key.input.value="";if(test){const result=await bridge.aiTest();status.textContent=result.ok?"AI provider connected.":result.error||"Provider test failed."}else status.textContent="AI provider saved.";await aiProviders()}catch(e){status.textContent=textError(e)}};
      const actions=n("div",undefined,"identity-actions"),saveButton=b("Save",()=>void save(false),"primary"),testButton=b("Save & test",()=>void save(true));actions.append(saveButton,testButton);detail.append(actions);
      const oauth=n("div",undefined,"connection-card");oauth.append(n("h3","OpenAI account"),n("p","Use device authorization without copying OAuth tokens into Integrations.","identity-muted"));if(bridge.aiOauth){const authBox=n("div"),start=selectAfter=>async()=>{try{status.textContent="Starting OpenAI authorization…";const flow=await bridge.aiOauth({action:"start"});authBox.replaceChildren();const link=n("a","Open verification page");link.href=flow.verificationUrl;link.target="_blank";link.rel="noopener noreferrer";authBox.append(n("p","Code: "+flow.userCode),link,b("Check authorization",async()=>{try{const out=await bridge.aiOauth({action:"poll",select:selectAfter});if(out.pending){status.textContent="Authorization is still pending.";return}status.textContent=out.selected?"OpenAI connected and selected.":"OpenAI connected.";await aiProviders()}catch(e){status.textContent=textError(e)}}));if(bridge.openLink)bridge.openLink(flow.verificationUrl)}catch(e){status.textContent=textError(e)}};const oauthActions=n("div",undefined,"identity-actions");oauthActions.append(b("Connect OpenAI",start(false)),b("Connect & use",start(true),"primary"));oauth.append(oauthActions,authBox)}detail.append(oauth);
      const custom=n("details",undefined,"connection-card");custom.append(n("summary","Add custom provider"));const cname=input("Provider name"),base=input("Base URL"),protocol=n("select"),protocolLabel=n("label","Protocol"),models=input("Models (comma separated)"),customKey=input("API key","","password");for(const id of["openai","anthropic"]){const o=n("option",id);o.value=id;protocol.append(o)}protocolLabel.append(protocol);const customFields=n("div",undefined,"identity-fields");customFields.append(cname.label,base.label,protocolLabel,models.label,customKey.label);custom.append(customFields,b("Add custom provider",async()=>{try{await bridge.aiSave({select:false,customProvider:{name:cname.input.value,baseURL:base.input.value,protocol:protocol.value,models:models.input.value.split(",").map(v=>v.trim()).filter(Boolean),apiKey:customKey.input.value}});status.textContent="Custom provider added.";await aiProviders()}catch(e){status.textContent=textError(e)}},"primary"));detail.append(custom);
      if(connected.length){detail.append(n("h3","Connected providers"));for(const row of connected){const card=n("div",undefined,"connection-card"),top=n("header",undefined,"connection-heading"),copy=n("div");copy.append(n("h3",meta.get(row.id)?.name||row.id),n("small",row.id+" · "+row.kind));top.append(copy,n("span",row.id===cfg.provider?"Active":row.hasKey?"Connected":"Configured","connection-state"));card.append(top,n("p",row.masked||"Credential stored server-side","identity-muted"));if(bridge.aiRemove){const disconnect=b("Disconnect",async()=>{if(!window.confirm("Disconnect "+row.id+"? Stored credentials for this AI provider will be removed."))return;try{await bridge.aiRemove(row.id);status.textContent="AI provider disconnected.";await aiProviders()}catch(e){status.textContent=textError(e)}},"danger");card.append(n("div",undefined,"identity-actions"));card.lastChild.append(disconnect)}detail.append(card)}}
    }catch(e){loading.remove();detail.append(n("p",textError(e),"identity-muted"))}
  }
  function drawProvider(){
    navMode="provider";activateNav(navMode);detail.replaceChildren();const heading=n("header",undefined,"provider-heading"),title=n("div",undefined,"provider-title"),copy=n("div");copy.append(n("h2",provider.title),n("p",provider.description));title.append(mark(provider),copy);heading.append(title);const add=b("Add connection",()=>user?newConnection():showProfiles(),"primary");add.disabled=!bridge.manage;heading.append(add);detail.append(heading);

    const rows=snapshot.connections.filter(c=>c.provider===provider.id);if(rows.length){const count=rows.filter(ready).length;detail.append(n("p",rows.length+" connection"+(rows.length===1?"":"s")+" · "+count+" verified","identity-summary-line"));}
    if(!rows.length){const empty=n("div",undefined,"identity-empty");empty.append(n("h3","Connect "+provider.title),n("p",user?"Add an account to start using "+provider.title+" in your projects.":bridge.manage?"Select a credential owner to add an account.":"Read the setup guide below, then sign in to connect your account."));const start=b("Add "+provider.title+" account",newConnection,"primary");start.disabled=!user||!bridge.manage;if(bridge.manage)empty.append(start);detail.append(empty);const help=n("details");help.append(n("summary","Connection methods & setup guides"));for(const s of provider.sources)for(const m of s.methods){const info=n("section");info.append(n("h3",s.label+" · "+m.label));guide(m,info);help.append(info)}detail.append(help)}
    for(const c of rows){const card=n("article",undefined,"connection-card");const top=n("header",undefined,"connection-heading"),name=n("div");name.append(n("h3",c.label),n("small",c.id));const state=n("span",stateLabel(c),"connection-state");state.dataset.ready=String(ready(c));top.append(name,state);card.append(top);const tags=n("div",undefined,"identity-tags");for(const value of [human(c.source),human(c.authMethod),c.sharedFrom?"Shared from "+c.sharedFrom.user:"",c.isDefault?"Default account":""])if(value)tags.append(n("span",value));card.append(tags);const actions=n("div",undefined,"identity-actions"),more=n("details",undefined,"identity-tools"),secondary=n("div",undefined,"identity-actions");more.append(n("summary","More"));more.append(secondary);
      if(provider.nativeGoogle&&!provider.configurationOnly){mountNativeGoogleConnection(card,c,{n,b,user,provider,catalog,snapshot,bridge,status,reload,selectProvider});detail.append(card);continue}
      const open=b(c.source==="direct"?(c.fields.some(f=>f.stored)?"Update credentials":"Finish setup"):"Authorize",()=>{if(c.source==="direct")void bridge.openSetup({user,provider:provider.id,connection:c.id}).catch(e=>status.textContent=textError(e));else external(c)});open.disabled=!bridge.manage;if(!c.sharedFrom)actions.append(open);
      const verify=b("Verify",async()=>{try{status.textContent="Checking selected connection…";const result=await bridge.execute({user,provider:provider.id,connection:c.id,operation:"verify"});await reload();status.textContent=(result.ok===true?"Verified: ":"Status: ")+result.detail}catch(e){status.textContent=textError(e)}});verify.disabled=!bridge.execute;actions.append(verify);
      const rename=b("Rename",()=>{detail.replaceChildren(n("h2","Rename connection"));const name=input("Label",c.label);detail.append(name.label,b("Save label",()=>change({action:"connection.rename",user,provider:provider.id,connection:c.id,label:name.input.value})),b("Cancel",()=>{navMode="provider";activateNav(navMode);drawProvider()}))});rename.disabled=!bridge.manage;secondary.append(rename);
      if(c.sharedFrom){card.append(n("p","Read-only shared backing: "+c.sharedFrom.user+" / "+c.sharedFrom.connection,"identity-muted"));}else if(c.source==="direct"){const fields=n("div",undefined,"identity-credential-status");for(const f of c.fields){const line=n("div");line.append(n("span",f.label));const fieldState=n("span",f.stored?"Stored":"Missing","credential-field-state");fieldState.dataset.stored=String(f.stored);line.append(fieldState);if(f.stored){const remove=b("Remove",()=>confirmation("Remove credential field",f.key,()=>change({action:"credential.delete",user,provider:provider.id,connection:c.id,key:f.key})),"danger");remove.disabled=!bridge.manage;line.append(remove)}fields.append(line)}card.append(fields);if(c.fields.some(f=>f.stored)){const clear=b("Clear credentials",()=>confirmation("Clear this connection's credential fields",c.id,()=>change({action:"credential.delete",user,provider:provider.id,connection:c.id})),"danger");clear.disabled=!bridge.manage;secondary.append(clear)}}
      if(!c.isDefault){const def=b("Make default",()=>change({action:"connection.default",user,provider:provider.id,connection:c.id}));def.disabled=!bridge.manage;secondary.append(def)}
      if(c.sharedFrom){const unshare=b("Unshare",()=>confirmation("Remove shared alias",c.id,()=>change({action:"connection.unshare",user,provider:provider.id,connection:c.id})),"danger");unshare.disabled=!bridge.manage;secondary.append(unshare)}else{if(c.source==="direct"&&!provider.nativeGoogle){const share=b("Share linked access",()=>shareConnection(c));share.disabled=!bridge.manage;secondary.append(share)}const duplicate=b("Copy to another owner",()=>copyConnection(c));duplicate.disabled=!bridge.manage;secondary.append(duplicate)}
      if(!c.sharedFrom){const del=b("Delete",()=>confirmation("Delete named connection",c.id,()=>change({action:"connection.delete",user,provider:provider.id,connection:c.id})),"danger");del.disabled=!bridge.manage;secondary.append(del);}actions.append(more);card.append(actions);if(c.lastCheck)card.append(n("small","Last checked "+new Date(c.lastCheck.checkedAt).toLocaleString()+" · "+stateLabel(c)));else if(c.verifiedAt)card.append(n("small","Last verified "+new Date(c.verifiedAt).toLocaleString()));detail.append(card);
    }
  }
  function newConnection(){
    detail.replaceChildren(n("h2","New "+provider.title+" connection"));const label=input("Connection label"),id=input("Connection ID"),source=n("select"),auth=n("select"),sourceLabel=n("label","Source / backend"),authLabel=n("label","Authentication method"),preview=n("div");source.setAttribute("aria-label","Source / backend");auth.setAttribute("aria-label","Authentication method");sourceLabel.append(source);authLabel.append(auth);
    label.input.addEventListener("input",()=>{if(!id.input.dataset.edited)id.input.value=label.input.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")});id.input.addEventListener("input",()=>id.input.dataset.edited="true");
    for(const s of provider.sources){const o=n("option",s.label);o.value=s.id;source.append(o)}
    function changeAuth(){auth.replaceChildren();for(const m of provider.sources.find(s=>s.id===source.value).methods){const o=n("option",m.label+" · "+m.scope);o.value=m.id;auth.append(o)}previewGuide()}
    function previewGuide(){preview.replaceChildren();const method=provider.sources.find(s=>s.id===source.value).methods.find(m=>m.id===auth.value);if(method.fields.length)preview.append(n("p","Fields: "+method.fields.map(f=>f.label+(f.required?" *":"")).join(", ")));else preview.append(n("p","No provider tokens are stored locally for this source."));guide(method,preview)}source.addEventListener("change",changeAuth);auth.addEventListener("change",previewGuide);changeAuth();
    const fields=n("div",undefined,"identity-fields");fields.append(label.label,sourceLabel,authLabel);const advanced=n("details");advanced.append(n("summary","Connection identifier"),id.label);detail.append(fields,advanced,preview,b("Create & connect",()=>change({action:"connection.create",user,provider:provider.id,connection:id.input.value,label:label.input.value,source:source.value,authMethod:auth.value},async()=>{await reload();if(provider.nativeGoogle&&!provider.configurationOnly)return;if(source.value==="direct")await bridge.openSetup({user,provider:provider.id,connection:id.input.value});else{const created=snapshot.connections.find(c=>c.provider===provider.id&&c.id===id.input.value);if(created)external(created)}}),"primary"),b("Cancel",()=>{navMode="provider";activateNav(navMode);drawProvider()}));label.input.focus();
  }
  function copyConnection(c){detail.replaceChildren(n("h2","Copy "+c.label),n("p","Creates an independent connection for another credential owner. Existing connections are never overwritten."));const targets=snapshot.users.filter(row=>row.id!==user).map(row=>({id:row.id,text:row.label+" · "+row.id})),target=choicePicker("Target credential owner",targets,targets[0]?.id||"",()=>sync()),id=input("New connection ID",c.id),label=input("New connection label",c.label),copy=input("","","checkbox"),make=input("","","checkbox");copy.label.className=make.label.className="identity-check";copy.label.append(document.createTextNode("Copy saved direct credentials"));copy.input.checked=c.source==="direct";copy.label.hidden=c.source!=="direct";make.label.append(document.createTextNode("Make the copied connection default for this service"));const submit=b("Copy connection",()=>change({action:"connection.duplicate",user,provider:provider.id,connection:c.id,target:target.value,targetConnection:id.input.value,label:label.input.value,copyCredentials:copy.input.checked,makeDefault:make.input.checked}),"primary"),sync=()=>{submit.disabled=!bridge.manage||!target.value||target.value===user||!id.input.value.trim()||!label.input.value.trim()};for(const control of[id.input,label.input])control.addEventListener("input",sync);sync();detail.append(target.wrap,id.label,label.label,copy.label,make.label,submit,b("Cancel",()=>{navMode="provider";activateNav(navMode);drawProvider()}));}
  function shareConnection(c){detail.replaceChildren(n("h2","Share "+c.label),n("p","Creates a read-only linked alias. Credential rotation stays with the current owner."));const targets=snapshot.users.filter(row=>row.id!==user).map(row=>({id:row.id,text:row.label+" · "+row.id})),target=choicePicker("Target credential owner",targets,targets[0]?.id||"",()=>sync()),label=input("New alias label",c.label),make=input("", "","checkbox");make.label.className="identity-check";make.label.append(document.createTextNode("Make this owner’s default for this service"));const submit=b("Create shared alias",()=>change({action:"connection.share",user,provider:provider.id,connection:c.id,target:target.value,label:label.input.value,makeDefault:make.input.checked}),"primary"),sync=()=>{submit.disabled=!bridge.manage||!target.value||target.value===user||!label.input.value.trim()};label.input.addEventListener("input",sync);sync();detail.append(target.wrap,label.label,make.label,submit,b("Cancel",()=>{navMode="provider";activateNav(navMode);drawProvider()}));}
  function external(c){
    detail.replaceChildren(n("h2",c.label),n("p",user+" / "+provider.id+" / "+c.source+" / "+c.authMethod));const method=provider.sources.find(s=>s.id===c.source).methods.find(m=>m.id===c.authMethod);guide(method);
    if(c.source==="native-mcp"){detail.append(n("p","Authorize in the provider's own MCP client. MSO will return this route, never substitute a stored API key."),b("Back",drawProvider));return}
    const broker=input("Composio project connection ID",c.external?.brokerConnection||""),config=input("Auth config ID (when several exist)",c.external?.authConfigId||""),managed=input("","","checkbox");managed.label.className="identity-check";managed.label.append(document.createTextNode("Allow creation of a managed OAuth config if none exists"));detail.append(broker.label,config.label,managed.label);
    const authorize=b("Open hosted authorization",async()=>{try{authorize.disabled=true;const result=await bridge.manage({action:"connection.authorize",confirm:true,user,provider:provider.id,connection:c.id,...(broker.input.value?{brokerConnection:broker.input.value}:{}),...(config.input.value?{authConfigId:config.input.value}:{}),createManaged:managed.input.checked});if(result.privateUrl){const a=n("a","Continue on Composio");a.href=result.privateUrl;a.rel="noopener noreferrer";a.target="_blank";a.addEventListener("click",e=>{if(bridge.openLink){e.preventDefault();bridge.openLink(result.privateUrl)}});detail.append(a)}status.textContent="Authorization pending. Complete the provider flow, then refresh status."}catch(e){status.textContent=textError(e);authorize.disabled=false}});authorize.disabled=Boolean(c.external?.connectedAccountId);detail.append(authorize,b("Refresh authorization status",async()=>{try{const result=await bridge.execute({user,provider:provider.id,connection:c.id,operation:"verify"});await reload();status.textContent=result.detail}catch(e){status.textContent=textError(e)}}),b("Back",drawProvider));
  }
  draw();if(bridge.query)void reload();
  return()=>{disposed=true;sequence++;root.replaceChildren();root.classList.remove("integration","manager")};
}
`;
