import { PROJECT_MCP_UI_SCRIPT } from "./project-mcp-ui";
export { CONNECTION_MANAGER_STYLE } from "./connection-ui-style";
import { PROVIDER_ICON_PATHS } from "./provider-icons";
export const CONNECTION_MANAGER_SCRIPT=PROJECT_MCP_UI_SCRIPT+`const PROVIDER_ICON_PATHS=${JSON.stringify(PROVIDER_ICON_PATHS)};`+String.raw`
function mountConnectionManager(root,catalog,bridge,initial={}){
  let disposed=false,sequence=0,snapshot=initial.snapshot||{users:[],connections:[],bindings:[]},user=initial.user||snapshot.user||null,provider=catalog.find(p=>p.id===initial.provider)||catalog.find(p=>p.id==="github")||catalog[0];
  let detail,status,container;
  const ready=c=>c.state==="verified"||c.state==="ACTIVE";
  const stateLabel=c=>ready(c)?"Verified":c.state==="incomplete"?"Needs setup":c.state==="configured"?"Not verified":c.state==="invalid"?"Access rejected":c.state==="unavailable"?"Check unavailable":c.state==="unconfigured"?"Needs setup":"Authorize";
  const mark=p=>{const wrap=n("span",undefined,"provider-mark"),svg=document.createElementNS("http://www.w3.org/2000/svg","svg"),shape=document.createElementNS("http://www.w3.org/2000/svg","path");wrap.setAttribute("aria-hidden","true");svg.setAttribute("viewBox","0 0 24 24");shape.setAttribute("d",PROVIDER_ICON_PATHS[p.id]||"M8 2h8v5h5v10h-5v5H8v-5H3V7h5V2zm2 2v5H5v6h5v5h4v-5h5V9h-5V4z");svg.append(shape);wrap.append(svg);return wrap};
  const human=s=>s.replaceAll("-"," ").replaceAll("_"," ");
  const n=(tag,text,cls)=>{const v=integrationNode(tag,text);if(cls)v.className=cls;return v};
  const b=(text,fn,cls)=>{const v=n("button",text,cls);v.type="button";v.addEventListener("click",fn);return v};
  const input=(label,value="",type="text")=>{const l=n("label",label),i=n("input");i.type=type;i.value=value;i.autocomplete="off";i.maxLength=120;l.append(i);return{label:l,input:i}};
  const choicePicker=(label,rows,selected,onChoose)=>{
    const wrap=n("div",undefined,"owner-picker"),caption=n("span",label,"identity-picker-label"),trigger=b("",()=>{popup.hidden?open():close()},"owner-picker-trigger"),popup=n("div",undefined,"owner-picker-popup");let value=selected||"";const options=[];
    wrap.setAttribute("role","group");wrap.setAttribute("aria-label",label);trigger.setAttribute("aria-haspopup","listbox");trigger.setAttribute("aria-expanded","false");popup.hidden=true;popup.setAttribute("role","listbox");popup.setAttribute("aria-label",label+" options");
    const current=()=>rows.find(row=>row.id===value),paint=()=>{const row=current();trigger.textContent=row?row.text:"Choose "+label.toLowerCase();for(const pair of options)pair[1].setAttribute("aria-selected",String(pair[0].id===value))};
    const close=(focus=false)=>{popup.hidden=true;trigger.setAttribute("aria-expanded","false");if(focus)trigger.focus()},open=()=>{popup.hidden=false;trigger.setAttribute("aria-expanded","true");const pair=options.find(pair=>pair[0].id===value)||options[0];pair?.[1].focus()},pick=row=>{value=row.id;paint();close(true);onChoose(row)};
    for(const row of rows){const option=b(row.text,()=>pick(row),"owner-picker-option");option.setAttribute("role","option");option.tabIndex=-1;options.push([row,option]);popup.append(option)}
    const move=(event,delta)=>{event.preventDefault();if(popup.hidden){open();return}const active=options.findIndex(pair=>pair[1]===document.activeElement),next=(active<0?(delta>0?0:options.length-1):(active+delta+options.length)%options.length);options[next]?.[1].focus()};
    trigger.addEventListener("keydown",event=>{if(event.key==="ArrowDown")move(event,1);else if(event.key==="ArrowUp")move(event,-1);else if(event.key==="Escape"){event.preventDefault();close()}});
    popup.addEventListener("keydown",event=>{if(event.key==="ArrowDown")move(event,1);else if(event.key==="ArrowUp")move(event,-1);else if(event.key==="Home"){event.preventDefault();options[0]?.[1].focus()}else if(event.key==="End"){event.preventDefault();options.at(-1)?.[1].focus()}else if(event.key==="Escape"){event.preventDefault();close(true)}});
    wrap.addEventListener("focusout",()=>setTimeout(()=>{if(!wrap.contains(document.activeElement))close()},0));wrap.append(caption,trigger,popup);paint();return{wrap,get value(){return value},set value(next){value=next;paint()}};
  };
  const textError=e=>({user_required:"Select a credential owner first.",connection_ambiguous:"Choose a named connection; more than one account exists.",connection_has_folder_binding:"Remove or change this connection's folder binding before deleting it.",connection_busy:"This connection is being used. Retry after that operation finishes.",choose_auth_config_id:"Several Composio auth configs match. Enter the intended auth config ID.",matching_auth_config_required:"Select a matching Composio auth config, or explicitly permit managed OAuth setup.",composio_project_key_required:"Configure a Composio project key under this same credential owner first.",external_source_requires_own_executor:"This connection uses an external backend; a local API key will not be substituted.",user_has_shared_dependents:"Unshare this owner’s shared connections before deleting the owner.",connection_has_shared_dependents:"Unshare dependent accounts before deleting this connection.",shared_alias_readonly:"Shared connections are read-only. Rotate credentials from the owner connection.",shared_alias_cannot_share:"A shared connection cannot be shared again. Share from its owner instead.",external_connections_cannot_share:"Only direct MSO credentials can be shared between credential owners.",shared_alias_use_unshare:"Use Unshare to remove a shared connection without touching its owner.",owner_required:"Sign in as an Owner before changing connections."}[e.code||e.message]||e.message||"Operation failed.");
  function remember(){if(bridge.remember)bridge.remember({user,provider:provider.id})}
  async function reload(){const version=++sequence;if(!bridge.query){draw();return}try{const next=await bridge.query({view:"snapshot",...(user?{user}:{})});if(disposed||version!==sequence)return;snapshot=next;user=next.user||user;draw();remember()}catch(e){if(!disposed){draw();status.textContent=textError(e)}}}
  async function change(args,after=reload){if(!bridge.manage)return;try{status.textContent="Saving connection metadata…";await bridge.manage({...args,confirm:true});await after()}catch(e){status.textContent=textError(e)}}
  function guide(method,parent=detail){const d=n("details",undefined,"identity-guide");d.open=parent!==detail;d.append(n("summary","How to get this credential / authorization"));const g=method.guidance,ol=n("ol");for(const step of g.steps)ol.append(n("li",step));d.append(ol);for(const[url,label]of [[g.url,"Official setup page"],[g.reference,"Documentation"]]){const a=n("a",label);a.href=url;a.rel="noopener noreferrer";a.target="_blank";if(bridge.openLink)a.addEventListener("click",e=>{e.preventDefault();Promise.resolve(bridge.openLink(url)).catch(error=>status.textContent=textError(error))});d.append(a)}parent.append(d)}
  function draw(){
    root.replaceChildren();root.classList.add("integration","manager");
    const heading=n("header",undefined,"identity-heading"),title=n("div");title.append(n(bridge.headingLevel===1?"h1":"h2","Integrations"),n("p","Connect your services. Choose the account each project uses."));heading.append(title,n("span",catalog.length+" services","identity-count"));root.append(heading);
    const toolbar=n("div",undefined,"identity-bar"),owner=choicePicker("Credential owner",snapshot.users.map(row=>({id:row.id,text:row.label+" · "+row.id+(row.isDefault?" · default":"")})),user,row=>{user=row.id;remember();void reload()});toolbar.append(owner.wrap,b("Refresh",reload));const workbench=n("div",undefined,"identity-actions identity-workbench");const usersAction=b("Users",profiles),routingAction=b("Routing",bindings);usersAction.disabled=routingAction.disabled=!bridge.manage;workbench.append(usersAction,routingAction);const transfer=b("Transfer",()=>bridge.openTransfer?bridge.openTransfer():bridge.openTransferBrowser?.());transfer.disabled=!bridge.openTransfer&&!bridge.openTransferBrowser;workbench.append(transfer);const addMcp=b("Add MCP",()=>mountProjectMcpForm(detail,bridge,snapshot,user,status,drawProvider,{n,b,input}),"primary");addMcp.disabled=!bridge.projectMcp;workbench.append(addMcp);toolbar.append(workbench);root.append(toolbar);
    if(!bridge.manage)root.append(n("p","Sign in as an MSO Owner to manage credentials. Device roles and credential users are different; the public guides remain available.","identity-readonly"));
    if(snapshot.connections.length){
      const summary=n("section",undefined,"identity-summary"),count=snapshot.connections.filter(ready).length,ring=n("div",undefined,"identity-ring");
      ring.style.setProperty("--ready-angle",(count/snapshot.connections.length*360)+"deg");ring.setAttribute("role","img");ring.setAttribute("aria-label",count+" of "+snapshot.connections.length+" connections verified");ring.append(n("strong",count));
      const stats=n("dl");for(const[label,value]of [["Verified",count],["Needs attention",snapshot.connections.length-count],["Project folders",snapshot.bindings.filter(row=>row.user===user).length]]){const item=n("div");item.append(n("dt",label),n("dd",value));stats.append(item)}summary.append(ring,stats);root.append(summary)
    }
    container=n("div",undefined,"identity-layout");const sidebar=n("nav",undefined,"identity-providers"),search=n("input");search.type="search";search.placeholder="Search services";search.setAttribute("aria-label","Search services");sidebar.setAttribute("aria-label","Services");sidebar.append(search);
    const buttons=[];for(const p of catalog){const item=b(undefined,()=>{provider=p;remember();drawProvider();for(const[row,button]of buttons)button.setAttribute("aria-pressed",String(row.id===provider.id))});item.append(mark(p),n("span",p.title));const count=snapshot.connections.filter(c=>c.provider===p.id).length;if(count)item.append(n("span",count,"provider-count"));item.setAttribute("aria-pressed",String(p.id===provider.id));buttons.push([p,item]);sidebar.append(item)}search.addEventListener("input",()=>{for(const[p,item]of buttons)item.hidden=!(p.title+" "+p.id).toLowerCase().includes(search.value.toLowerCase())});
    detail=n("section",undefined,"identity-detail");status=n("p",undefined,"identity-feedback");status.setAttribute("role","status");status.setAttribute("aria-live","polite");container.append(sidebar,detail);root.append(container,status);drawProvider();
  }
  function confirmation(title,id,fn){detail.replaceChildren(n("h2",title),n("p","This changes only the selected identity. Type “"+id+"” to confirm."));const value=input("Confirmation");detail.append(value.label,b("Confirm",()=>{if(value.input.value!==id){status.textContent="Confirmation does not match.";return}void fn()},"danger"),b("Cancel",drawProvider));}
  function profiles(){
    detail.replaceChildren(n("h2","Credential owners"),n("p","These profiles isolate service accounts. They do not grant MSO device roles."));
    const id=input("New user ID"),name=input("Display label");detail.append(id.label,name.label);const create=b("Create user",()=>change({action:"user.create",user:id.input.value,label:name.input.value||id.input.value},async()=>{user=id.input.value;await reload()}),"primary");create.disabled=!bridge.manage;detail.append(create);
    if(!user)return;const current=snapshot.users.find(u=>u.id===user);detail.append(n("h3",current?.label||user));
    const target=input("Target user ID"),label=input("New display label",current?.label||user),copy=input("", "","checkbox");copy.input.checked=false;copy.label.className="identity-check";copy.label.append(document.createTextNode("Copy saved direct credentials when duplicating (otherwise metadata only)"));
    detail.append(target.label,label.label,copy.label);const row=n("div",undefined,"identity-actions");
    for(const[text,action]of [["Rename user","user.rename"],["Duplicate user","user.duplicate"]]){const button=b(text,()=>change({action,user,target:target.input.value,label:label.input.value,...(action==="user.duplicate"?{copyCredentials:copy.input.checked}:{})},async()=>{user=target.input.value;await reload()}));button.disabled=!bridge.manage;row.append(button)}
    const def=b("Set default user",()=>change({action:"user.default",user}));def.disabled=!bridge.manage;row.append(def);const del=b("Delete user",()=>confirmation("Delete credential owner",user,()=>change({action:"user.delete",user},async()=>{user=null;await reload()})),"danger");del.disabled=!bridge.manage;row.append(del);detail.append(row);
  }
  function bindings(){
    detail.replaceChildren(n("h2","Folder → credential context"),n("p","The longest matching folder selects its credential user and optional provider connection. It never changes another user's defaults."));
    const folder=input("Absolute project folder"),connection=input("Connection ID (optional)");detail.append(folder.label,connection.label);const save=b("Bind this folder",()=>change({action:"folder.map",path:folder.input.value,user,...(connection.input.value?{provider:provider.id,connection:connection.input.value}:{})}));save.disabled=!user||!bridge.manage;detail.append(save);
    for(const binding of snapshot.bindings){const card=n("div",undefined,"connection-card");card.append(n("strong",binding.path),n("p",binding.user+" · "+Object.entries(binding.connections).map(([p,id])=>p+"="+id).join(", ")));const remove=b("Remove binding",()=>change({action:"folder.unmap",path:binding.path}));remove.disabled=!bridge.manage;card.append(remove);detail.append(card)}
  }
  function drawProvider(){
    detail.replaceChildren();const heading=n("header",undefined,"provider-heading"),title=n("div",undefined,"provider-title"),copy=n("div");copy.append(n("h2",provider.title),n("p",provider.description));title.append(mark(provider),copy);heading.append(title);detail.append(heading);
    const create=b("New connection",newConnection,"primary");create.disabled=!user||!bridge.manage;if(bridge.manage)heading.append(create);
    const rows=snapshot.connections.filter(c=>c.provider===provider.id);
    if(!rows.length){const empty=n("div",undefined,"identity-empty");empty.append(n("h3","Connect "+provider.title),n("p",user?"Add an account to start using "+provider.title+" in your projects.":bridge.manage?"Select a credential owner to add an account.":"Read the setup guide below, then sign in to connect your account."));const start=b("Add "+provider.title+" account",newConnection,"primary");start.disabled=!user||!bridge.manage;if(bridge.manage)empty.append(start);detail.append(empty);const help=n("details");help.append(n("summary","Connection methods & setup guides"));for(const s of provider.sources)for(const m of s.methods){const info=n("section");info.append(n("h3",s.label+" · "+m.label));guide(m,info);help.append(info)}detail.append(help)}
    for(const c of rows){const card=n("article",undefined,"connection-card");const top=n("header",undefined,"connection-heading"),name=n("div");name.append(n("h3",c.label),n("small",c.id));const state=n("span",stateLabel(c),"connection-state");state.dataset.ready=String(ready(c));top.append(name,state);card.append(top);const tags=n("div",undefined,"identity-tags");for(const value of [human(c.source),human(c.authMethod),c.sharedFrom?"Shared from "+c.sharedFrom.user:"",c.isDefault?"Default account":""])if(value)tags.append(n("span",value));card.append(tags);const actions=n("div",undefined,"identity-actions"),more=n("details",undefined,"identity-tools"),secondary=n("div",undefined,"identity-actions");more.append(n("summary","More"));more.append(secondary);
      const open=b(c.source==="direct"?(c.fields.some(f=>f.stored)?"Update credentials":"Finish setup"):"Authorize",()=>{if(c.source==="direct")void bridge.openSetup({user,provider:provider.id,connection:c.id}).catch(e=>status.textContent=textError(e));else external(c)});open.disabled=!bridge.manage;if(!c.sharedFrom)actions.append(open);
      const verify=b("Verify",async()=>{try{status.textContent="Checking selected connection…";const result=await bridge.execute({user,provider:provider.id,connection:c.id,operation:"verify"});await reload();status.textContent=(result.ok===true?"Verified: ":"Status: ")+result.detail}catch(e){status.textContent=textError(e)}});verify.disabled=!bridge.execute;actions.append(verify);
      const rename=b("Rename",()=>{detail.replaceChildren(n("h2","Rename connection"));const name=input("Label",c.label);detail.append(name.label,b("Save label",()=>change({action:"connection.rename",user,provider:provider.id,connection:c.id,label:name.input.value})),b("Cancel",drawProvider))});rename.disabled=!bridge.manage;secondary.append(rename);
      if(c.sharedFrom){card.append(n("p","Read-only shared backing: "+c.sharedFrom.user+" / "+c.sharedFrom.connection,"identity-muted"));}else if(c.source==="direct"){const fields=n("div",undefined,"identity-credential-status");for(const f of c.fields){const line=n("div");line.append(n("span",f.label));const fieldState=n("span",f.stored?"Stored":"Missing","credential-field-state");fieldState.dataset.stored=String(f.stored);line.append(fieldState);if(f.stored){const remove=b("Remove",()=>confirmation("Remove credential field",f.key,()=>change({action:"credential.delete",user,provider:provider.id,connection:c.id,key:f.key})),"danger");remove.disabled=!bridge.manage;line.append(remove)}fields.append(line)}card.append(fields);if(c.fields.some(f=>f.stored)){const clear=b("Clear credentials",()=>confirmation("Clear this connection's credential fields",c.id,()=>change({action:"credential.delete",user,provider:provider.id,connection:c.id})),"danger");clear.disabled=!bridge.manage;secondary.append(clear)}}
      if(!c.isDefault){const def=b("Make default",()=>change({action:"connection.default",user,provider:provider.id,connection:c.id}));def.disabled=!bridge.manage;secondary.append(def)}
      if(c.sharedFrom){const unshare=b("Unshare",()=>confirmation("Remove shared alias",c.id,()=>change({action:"connection.unshare",user,provider:provider.id,connection:c.id})),"danger");unshare.disabled=!bridge.manage;secondary.append(unshare)}else if(c.source==="direct"){const share=b("Share",()=>shareConnection(c));share.disabled=!bridge.manage;secondary.append(share)}
      if(!c.sharedFrom){const del=b("Delete",()=>confirmation("Delete named connection",c.id,()=>change({action:"connection.delete",user,provider:provider.id,connection:c.id})),"danger");del.disabled=!bridge.manage;secondary.append(del);}actions.append(more);card.append(actions);if(c.lastCheck)card.append(n("small","Last checked "+new Date(c.lastCheck.checkedAt).toLocaleString()+" · "+stateLabel(c)));else if(c.verifiedAt)card.append(n("small","Last verified "+new Date(c.verifiedAt).toLocaleString()));detail.append(card);
    }
  }
  function newConnection(){
    detail.replaceChildren(n("h2","New "+provider.title+" connection"));const label=input("Connection label"),id=input("Connection ID"),source=n("select"),auth=n("select"),sourceLabel=n("label","Source / backend"),authLabel=n("label","Authentication method"),preview=n("div");source.setAttribute("aria-label","Source / backend");auth.setAttribute("aria-label","Authentication method");sourceLabel.append(source);authLabel.append(auth);
    label.input.addEventListener("input",()=>{if(!id.input.dataset.edited)id.input.value=label.input.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")});id.input.addEventListener("input",()=>id.input.dataset.edited="true");
    for(const s of provider.sources){const o=n("option",s.label);o.value=s.id;source.append(o)}
    function changeAuth(){auth.replaceChildren();for(const m of provider.sources.find(s=>s.id===source.value).methods){const o=n("option",m.label+" · "+m.scope);o.value=m.id;auth.append(o)}previewGuide()}
    function previewGuide(){preview.replaceChildren();const method=provider.sources.find(s=>s.id===source.value).methods.find(m=>m.id===auth.value);if(method.fields.length)preview.append(n("p","Fields: "+method.fields.map(f=>f.label+(f.required?" *":"")).join(", ")));else preview.append(n("p","No provider tokens are stored locally for this source."));guide(method,preview)}source.addEventListener("change",changeAuth);auth.addEventListener("change",previewGuide);changeAuth();
    const fields=n("div",undefined,"identity-fields");fields.append(label.label,sourceLabel,authLabel);const advanced=n("details");advanced.append(n("summary","Connection identifier"),id.label);detail.append(fields,advanced,preview,b("Create & connect",()=>change({action:"connection.create",user,provider:provider.id,connection:id.input.value,label:label.input.value,source:source.value,authMethod:auth.value},async()=>{await reload();if(source.value==="direct")await bridge.openSetup({user,provider:provider.id,connection:id.input.value});else{const created=snapshot.connections.find(c=>c.provider===provider.id&&c.id===id.input.value);if(created)external(created)}}),"primary"),b("Cancel",drawProvider));label.input.focus();
  }
  function shareConnection(c){detail.replaceChildren(n("h2","Share "+c.label),n("p","Creates a read-only direct alias. The owner keeps control of credential rotation."));const targets=snapshot.users.filter(row=>row.id!==user).map(row=>({id:row.id,text:row.label+" · "+row.id})),target=choicePicker("Target credential owner",targets,targets[0]?.id||"",()=>sync()),label=input("New alias label",c.label),make=input("", "","checkbox");make.label.className="identity-check";make.label.append(document.createTextNode("Make this owner’s default for this service"));const submit=b("Create shared alias",()=>change({action:"connection.share",user,provider:provider.id,connection:c.id,target:target.value,label:label.input.value,makeDefault:make.input.checked}),"primary"),sync=()=>{submit.disabled=!bridge.manage||!target.value||target.value===user||!label.input.value.trim()};label.input.addEventListener("input",sync);sync();detail.append(target.wrap,label.label,make.label,submit,b("Cancel",drawProvider));}
  function external(c){
    detail.replaceChildren(n("h2",c.label),n("p",user+" / "+provider.id+" / "+c.source+" / "+c.authMethod));const method=provider.sources.find(s=>s.id===c.source).methods.find(m=>m.id===c.authMethod);guide(method);
    if(c.source==="native-mcp"){detail.append(n("p","Authorize in the provider's own MCP client. MSO will return this route, never substitute a stored API key."),b("Back",drawProvider));return}
    const broker=input("Composio project connection ID",c.external?.brokerConnection||""),config=input("Auth config ID (when several exist)",c.external?.authConfigId||""),managed=input("","","checkbox");managed.label.className="identity-check";managed.label.append(document.createTextNode("Allow creation of a managed OAuth config if none exists"));detail.append(broker.label,config.label,managed.label);
    const authorize=b("Open hosted authorization",async()=>{try{authorize.disabled=true;const result=await bridge.manage({action:"connection.authorize",confirm:true,user,provider:provider.id,connection:c.id,...(broker.input.value?{brokerConnection:broker.input.value}:{}),...(config.input.value?{authConfigId:config.input.value}:{}),createManaged:managed.input.checked});if(result.privateUrl){const a=n("a","Continue on Composio");a.href=result.privateUrl;a.rel="noopener noreferrer";a.target="_blank";a.addEventListener("click",e=>{if(bridge.openLink){e.preventDefault();bridge.openLink(result.privateUrl)}});detail.append(a)}status.textContent="Authorization pending. Complete the provider flow, then refresh status."}catch(e){status.textContent=textError(e);authorize.disabled=false}});authorize.disabled=Boolean(c.external?.connectedAccountId);detail.append(authorize,b("Refresh authorization status",async()=>{try{const result=await bridge.execute({user,provider:provider.id,connection:c.id,operation:"verify"});await reload();status.textContent=result.detail}catch(e){status.textContent=textError(e)}}),b("Back",drawProvider));
  }
  draw();if(bridge.query)void reload();
  return()=>{disposed=true;sequence++;root.replaceChildren();root.classList.remove("integration","manager")};
}
`;
