// One metadata-only manager for browser, CLI-opened browser and MCP Page.
// Only mountIntegrationForm handles secrets, using its direct HTTPS capability.
export const CONNECTION_MANAGER_STYLE=String.raw`
.integration .identity-bar{display:flex;gap:10px;align-items:end;flex-wrap:wrap;margin:14px 0 20px}.integration .identity-bar>label{flex:1;min-width:170px;margin:0}.integration .identity-bar select{margin-top:6px}.integration .identity-layout{display:grid;grid-template-columns:220px minmax(0,1fr);gap:20px}.integration .identity-providers{display:grid;gap:7px;align-content:start;max-height:560px;overflow:auto}.integration .identity-providers button{display:block;text-align:left;padding:10px 12px;min-height:42px}.integration [aria-pressed=true]{border-color:var(--os-accent);background:color-mix(in srgb,var(--os-accent) 10%,var(--surface))}.integration .connection-card{border:1px solid var(--sep-strong);border-radius:12px;padding:16px;margin:12px 0;background:var(--field)}.integration .connection-card h3{margin:0 0 6px;font-size:18px}.integration .identity-tags{display:flex;flex-wrap:wrap;gap:5px;margin:8px 0}.integration .identity-tags span{padding:3px 7px;border:1px solid var(--sep-strong);border-radius:99px;font-size:11px;color:var(--text-dim)}.integration .identity-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.integration .identity-fields{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:14px 0}.integration .identity-fields label{min-width:0}.integration .identity-fields input,.integration .identity-fields select{margin-top:6px}.integration .identity-feedback{min-height:24px;margin:8px 0;color:var(--text-dim);overflow-wrap:anywhere}.integration .identity-path{font:12px var(--font-mono);overflow-wrap:anywhere;margin:8px 0 15px}.integration .identity-check{display:flex;align-items:center;gap:8px}.integration .identity-check input{width:18px;height:18px;flex:none}.integration .identity-empty{border:1px dashed var(--sep-strong);border-radius:12px;padding:22px}.integration .identity-detail{min-width:0}.integration .identity-detail h2{font-size:22px}.integration .danger{color:var(--destructive-text)}.integration .identity-guide a{display:inline-block;margin:8px 12px 5px 0}.integration .identity-guide li{font-size:13px}.integration .identity-muted{font-size:12px;color:var(--text-dim)}.integration .identity-form{border:1px solid var(--sep-strong);border-radius:12px;padding:16px}.integration .identity-readonly{padding:10px 14px;border-left:3px solid var(--os-accent);background:var(--field);font-size:13px}@media(max-width:640px){.integration .identity-layout{grid-template-columns:1fr;gap:12px}.integration .identity-providers{grid-template-columns:1fr 1fr;max-height:180px}.integration .identity-providers input{grid-column:1/-1}.integration .identity-fields{grid-template-columns:1fr}.integration .identity-bar{gap:7px}.integration .connection-card{padding:13px}}
`;
export const CONNECTION_MANAGER_SCRIPT=String.raw`
function mountConnectionManager(root,catalog,bridge,initial={}){
  let disposed=false,sequence=0,snapshot=initial.snapshot||{users:[],connections:[],bindings:[]},user=initial.user||snapshot.user||null,provider=catalog.find(p=>p.id===initial.provider)||catalog.find(p=>p.id==="github")||catalog[0];
  let detail,status,container;
  const n=(tag,text,cls)=>{const v=integrationNode(tag,text);if(cls)v.className=cls;return v};
  const b=(text,fn,cls)=>{const v=n("button",text,cls);v.type="button";v.addEventListener("click",fn);return v};
  const input=(label,value="",type="text")=>{const l=n("label",label),i=n("input");i.type=type;i.value=value;i.autocomplete="off";i.maxLength=120;l.append(i);return{label:l,input:i}};
  const textError=e=>({user_required:"Select a credential owner first.",connection_ambiguous:"Choose a named connection; more than one account exists.",connection_has_folder_binding:"Remove or change this connection's folder binding before deleting it.",connection_busy:"This connection is being used. Retry after that operation finishes.",choose_auth_config_id:"Several Composio auth configs match. Enter the intended auth config ID.",matching_auth_config_required:"Select a matching Composio auth config, or explicitly permit managed OAuth setup.",composio_project_key_required:"Configure a Composio project key under this same credential owner first.",external_source_requires_own_executor:"This connection uses an external backend; a local API key will not be substituted.",owner_required:"Sign in as an Owner before changing connections."}[e.code||e.message]||e.message||"Operation failed.");
  function remember(){if(bridge.remember)bridge.remember({user,provider:provider.id})}
  async function reload(){const version=++sequence;if(!bridge.query){draw();return}try{const next=await bridge.query({view:"snapshot",...(user?{user}:{})});if(disposed||version!==sequence)return;snapshot=next;user=next.user||user;draw();remember()}catch(e){if(!disposed){draw();status.textContent=textError(e)}}}
  async function change(args,after=reload){if(!bridge.manage)return;try{status.textContent="Saving connection metadata…";await bridge.manage({...args,confirm:true});await after()}catch(e){status.textContent=textError(e)}}
  function guide(method,parent=detail){const d=n("details",undefined,"identity-guide");d.open=true;d.append(n("summary","How to get this credential / authorization"));const g=method.guidance,ol=n("ol");for(const step of g.steps)ol.append(n("li",step));d.append(ol);for(const[url,label]of [[g.url,"Official setup page"],[g.reference,"Documentation"]]){const a=n("a",label);a.href=url;a.rel="noopener noreferrer";a.target="_blank";if(bridge.openLink)a.addEventListener("click",e=>{e.preventDefault();Promise.resolve(bridge.openLink(url)).catch(error=>status.textContent=textError(error))});d.append(a)}parent.append(d)}
  function draw(){
    root.replaceChildren();root.classList.add("integration");root.append(n("h2","Integrations"),n("p","Credential owners, named accounts and deployments — shared by MSO CLI, tools and this form."));
    const toolbar=n("div",undefined,"identity-bar"),label=n("label","Credential owner"),select=n("select");select.setAttribute("aria-label","Credential owner");const placeholder=n("option","Choose a user");placeholder.value="";select.append(placeholder);
    for(const row of snapshot.users){const o=n("option",row.label+" ("+row.id+")"+(row.isDefault?" · default":""));o.value=row.id;select.append(o)}select.value=user||"";select.addEventListener("change",()=>{user=select.value||null;remember();void reload()});label.append(select);toolbar.append(label,b("Manage users",profiles),b("Folder bindings",bindings),b("Refresh",reload));root.append(toolbar);
    if(!bridge.manage)root.append(n("p","Sign in as an MSO Owner to manage credentials. Device roles and credential users are different; the public guides remain available.","identity-readonly"));
    container=n("div",undefined,"identity-layout");const sidebar=n("nav",undefined,"identity-providers"),search=n("input");search.type="search";search.placeholder="Search services";search.setAttribute("aria-label","Search services");sidebar.append(search);
    const buttons=[];for(const p of catalog){const item=b(p.title,()=>{provider=p;remember();drawProvider();for(const[row,button]of buttons)button.setAttribute("aria-pressed",String(row.id===provider.id))});item.setAttribute("aria-pressed",String(p.id===provider.id));buttons.push([p,item]);sidebar.append(item)}search.addEventListener("input",()=>{for(const[p,item]of buttons)item.hidden=!(p.title+" "+p.id).toLowerCase().includes(search.value.toLowerCase())});
    detail=n("section",undefined,"identity-detail");status=n("p",undefined,"identity-feedback");status.setAttribute("role","status");status.setAttribute("aria-live","polite");container.append(sidebar,detail);root.append(container,status);drawProvider();
  }
  function confirmation(title,id,fn){detail.replaceChildren(n("h2",title),n("p","This changes only the selected identity. Type “"+id+"” to confirm."));const value=input("Confirmation");detail.append(value.label,b("Confirm",()=>{if(value.input.value!==id){status.textContent="Confirmation does not match.";return}void fn()},"danger"),b("Cancel",drawProvider));}
  function profiles(){
    detail.replaceChildren(n("h2","Credential owners"),n("p","These profiles isolate service accounts. They do not grant MSO device roles."));
    const id=input("New user ID"),name=input("Display label");detail.append(id.label,name.label);const create=b("Create user",()=>change({action:"user.create",user:id.input.value,label:name.input.value||id.input.value},async()=>{user=id.input.value;await reload()}),"primary");create.disabled=!bridge.manage;detail.append(create);
    if(!user)return;const current=snapshot.users.find(u=>u.id===user);detail.append(n("h3",current?.label||user));
    const target=input("Target user ID"),label=input("New display label",current?.label||user),copy=input("", "","checkbox");copy.input.checked=false;copy.label.className="identity-check";copy.label.append(document.createTextNode("Copy saved direct credentials when duplicating (otherwise metadata only)"));
    detail.append(target.label,label.label,copy.label);const row=n("div",undefined,"identity-actions");
    for(const[text,action]of [["Rename user","user.rename"],["Duplicate user","user.duplicate"]]){const button=b(text,()=>change({action,user,target:target.input.value,label:label.input.value,...(action==="user.duplicate"?{copyCredentials:copy.input.checked}:{})},async()=>{user=target.input.value;await reload()}));button.disabled=!bridge.manage;row.append(button)}
    const def=b("Set default user",()=>change({action:"user.default",user}));def.disabled=!bridge.manage;row.append(def);const del=b("Delete user",()=>confirmation("Delete credential owner",user,()=>change({action:"user.delete",user},async()=>{user=null;await reload()})),"danger");del.disabled=!bridge.manage;row.append(del);detail.append(row);
  }
  function bindings(){
    detail.replaceChildren(n("h2","Folder → credential context"),n("p","The longest matching folder selects its credential user and optional provider connection. It never changes another user's defaults."));
    const folder=input("Absolute project folder"),connection=input("Connection ID (optional)");detail.append(folder.label,connection.label);const save=b("Bind this folder",()=>change({action:"folder.map",path:folder.input.value,user,...(connection.input.value?{provider:provider.id,connection:connection.input.value}:{})}));save.disabled=!user||!bridge.manage;detail.append(save);
    for(const binding of snapshot.bindings){const card=n("div",undefined,"connection-card");card.append(n("strong",binding.path),n("p",binding.user+" · "+Object.entries(binding.connections).map(([p,id])=>p+"="+id).join(", ")));const remove=b("Remove binding",()=>change({action:"folder.unmap",path:binding.path}));remove.disabled=!bridge.manage;card.append(remove);detail.append(card)}
  }
  function drawProvider(){
    detail.replaceChildren(n("h2",provider.title),n("p",provider.description),n("div",(user||"Choose user")+" → "+provider.id+" → Connection → Source → Auth","identity-path"));
    const create=b("New connection",newConnection,"primary");create.disabled=!user||!bridge.manage;detail.append(create);
    const rows=snapshot.connections.filter(c=>c.provider===provider.id);
    if(!rows.length){detail.append(n("p","No named connection for this user. Create one before entering credentials.","identity-empty"));for(const s of provider.sources)for(const m of s.methods){const info=n("details");info.append(n("summary",s.label+" · "+m.label));guide(m,info);detail.append(info)}}
    for(const c of rows){const card=n("article",undefined,"connection-card");card.append(n("h3",c.label),n("small",c.id));const tags=n("div",undefined,"identity-tags");for(const value of [c.source,c.authMethod,c.scope,c.state,c.isDefault?"default":""])if(value)tags.append(n("span",value));card.append(tags);const actions=n("div",undefined,"identity-actions");
      const open=b(c.source==="direct"?"Set / rotate credentials":"Authorization",()=>{if(c.source==="direct")void bridge.openSetup({user,provider:provider.id,connection:c.id}).catch(e=>status.textContent=textError(e));else external(c)});open.disabled=!bridge.manage;actions.append(open);
      const verify=b("Verify",async()=>{try{status.textContent="Checking selected connection…";const result=await bridge.execute({user,provider:provider.id,connection:c.id,operation:"verify"});status.textContent=(result.ok===true?"Verified: ":"Status: ")+result.detail}catch(e){status.textContent=textError(e)}});verify.disabled=!bridge.execute;actions.append(verify);
      const rename=b("Rename",()=>{detail.replaceChildren(n("h2","Rename connection"));const name=input("Label",c.label);detail.append(name.label,b("Save label",()=>change({action:"connection.rename",user,provider:provider.id,connection:c.id,label:name.input.value})),b("Cancel",drawProvider))});rename.disabled=!bridge.manage;actions.append(rename);
      if(c.source==="direct"&&c.fields.some(f=>f.stored)){const clear=b("Clear credentials",()=>confirmation("Clear this connection's credential fields",c.id,()=>change({action:"credential.delete",user,provider:provider.id,connection:c.id})),"danger");clear.disabled=!bridge.manage;actions.append(clear)}
      if(!c.isDefault){const def=b("Make default",()=>change({action:"connection.default",user,provider:provider.id,connection:c.id}));def.disabled=!bridge.manage;actions.append(def)}
      const del=b("Delete",()=>confirmation("Delete named connection",c.id,()=>change({action:"connection.delete",user,provider:provider.id,connection:c.id})),"danger");del.disabled=!bridge.manage;actions.append(del);card.append(actions);detail.append(card);
    }
  }
  function newConnection(){
    detail.replaceChildren(n("h2","New "+provider.title+" connection"));const label=input("Connection label"),id=input("Connection ID"),source=n("select"),auth=n("select"),sourceLabel=n("label","Source / backend"),authLabel=n("label","Authentication method"),preview=n("div");source.setAttribute("aria-label","Source / backend");auth.setAttribute("aria-label","Authentication method");sourceLabel.append(source);authLabel.append(auth);
    label.input.addEventListener("input",()=>{if(!id.input.dataset.edited)id.input.value=label.input.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")});id.input.addEventListener("input",()=>id.input.dataset.edited="true");
    for(const s of provider.sources){const o=n("option",s.label);o.value=s.id;source.append(o)}
    function changeAuth(){auth.replaceChildren();for(const m of provider.sources.find(s=>s.id===source.value).methods){const o=n("option",m.label+" · "+m.scope);o.value=m.id;auth.append(o)}previewGuide()}
    function previewGuide(){preview.replaceChildren();const method=provider.sources.find(s=>s.id===source.value).methods.find(m=>m.id===auth.value);if(method.fields.length)preview.append(n("p","Fields: "+method.fields.map(f=>f.label+(f.required?" *":"")).join(", ")));else preview.append(n("p","No provider tokens are stored locally for this source."));guide(method,preview)}source.addEventListener("change",changeAuth);auth.addEventListener("change",previewGuide);changeAuth();
    const fields=n("div",undefined,"identity-fields");fields.append(label.label,id.label,sourceLabel,authLabel);detail.append(fields,preview,b("Create connection",()=>change({action:"connection.create",user,provider:provider.id,connection:id.input.value,label:label.input.value,source:source.value,authMethod:auth.value}),"primary"),b("Cancel",drawProvider));
  }
  function external(c){
    detail.replaceChildren(n("h2",c.label),n("p",user+" / "+provider.id+" / "+c.source+" / "+c.authMethod));const method=provider.sources.find(s=>s.id===c.source).methods.find(m=>m.id===c.authMethod);guide(method);
    if(c.source==="native-mcp"){detail.append(n("p","Authorize in the provider's own MCP client. MSO will return this route, never substitute a stored API key."),b("Back",drawProvider));return}
    const broker=input("Composio project connection ID",c.external?.brokerConnection||""),config=input("Auth config ID (when several exist)",c.external?.authConfigId||""),managed=input("","","checkbox");managed.label.className="identity-check";managed.label.append(document.createTextNode("Allow creation of a managed OAuth config if none exists"));detail.append(broker.label,config.label,managed.label);
    const authorize=b("Open hosted authorization",async()=>{try{authorize.disabled=true;const result=await bridge.manage({action:"connection.authorize",confirm:true,user,provider:provider.id,connection:c.id,...(broker.input.value?{brokerConnection:broker.input.value}:{}),...(config.input.value?{authConfigId:config.input.value}:{}),createManaged:managed.input.checked});if(result.privateUrl){const a=n("a","Continue on Composio");a.href=result.privateUrl;a.rel="noopener noreferrer";a.target="_blank";a.addEventListener("click",e=>{if(bridge.openLink){e.preventDefault();bridge.openLink(result.privateUrl)}});detail.append(a)}status.textContent="Authorization pending. Complete the provider flow, then refresh status."}catch(e){status.textContent=textError(e);authorize.disabled=false}});authorize.disabled=Boolean(c.external?.connectedAccountId);detail.append(authorize,b("Refresh authorization status",async()=>{try{const result=await bridge.execute({user,provider:provider.id,connection:c.id,operation:"verify"});status.textContent=result.detail}catch(e){status.textContent=textError(e)}}),b("Back",drawProvider));
  }
  draw();if(bridge.query)void reload();
  return()=>{disposed=true;sequence++;root.replaceChildren();root.classList.remove("integration")};
}
`;
