export const INTEGRATION_PICKER_STYLE = String.raw`
.integration{max-width:1100px;width:100%;margin:0 auto}.integration .picker-header{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:22px}.integration .picker-header h2{margin:0;font-size:26px}.integration .picker-header p{max-width:630px;margin:7px 0}.integration .picker-layout{display:grid;grid-template-columns:minmax(210px,280px) minmax(0,1fr);gap:22px}.integration .provider-list{display:grid;gap:7px;margin-top:12px;max-height:490px;overflow:auto;padding-right:4px}.integration .provider-option{display:block;text-align:left;width:100%;border:1px solid var(--sep-strong);background:var(--field);color:var(--text);padding:11px 12px;border-radius:10px;font:600 14px var(--font-body);cursor:pointer}.integration .provider-option[aria-pressed=true]{border-color:var(--os-accent);background:color-mix(in srgb,var(--os-accent) 12%,var(--surface))}.integration .provider-option small{margin-top:2px;font-size:11px;font-weight:400}.integration .provider-detail{border:1px solid var(--sep-strong);border-radius:14px;padding:20px;background:var(--field);min-width:0}.integration .provider-detail h3{font:700 22px var(--font-display);margin:0 0 8px}.integration .provider-detail label{font-size:13px}.integration .provider-fields{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0 18px}.integration .field-tag{font:12px var(--font-body);padding:5px 9px;border:1px solid var(--sep-strong);border-radius:7px;color:var(--text-dim)}.integration .picker-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.integration .picker-note{padding:12px 14px;border-left:3px solid var(--os-accent);background:color-mix(in srgb,var(--os-accent) 7%,var(--surface));border-radius:7px;font-size:12px}.integration .picker-feedback{min-height:22px;margin:10px 0 0;font-size:13px;overflow-wrap:anywhere}.integration .back-link{margin-bottom:14px}.integration [type=search]{font-size:15px}.integration .setup-grid{margin-top:18px}@media(max-width:640px){.integration .picker-layout{grid-template-columns:1fr;gap:14px}.integration .provider-list{grid-template-columns:repeat(2,minmax(0,1fr));max-height:220px;padding:0}.integration .provider-detail{padding:15px}.integration .picker-header{display:block}.integration .provider-option{min-height:55px}}@media(max-width:360px){.integration .provider-list{grid-template-columns:1fr}}
`;
export const INTEGRATION_PICKER_SCRIPT = String.raw`
function mountIntegrationPicker(root,catalog,options={}){
  root.replaceChildren();root.classList.add("integration");
  const node=(tag,text,className)=>{const n=integrationNode(tag,text);if(className)n.className=className;return n};
  const button=(label,handler,className)=>{const b=node("button",label,className);b.type="button";b.addEventListener("click",handler);return b};
  const header=node("header",undefined,"picker-header"),head=node("div");head.append(node("h2","Integrations"),node("p","Connect services directly to MSO. Review the official steps first, then enter your credential in a private form."));header.append(head);if(options.session){const status=node("p","Checking MSO session…","picker-note");status.id="integration-auth-status";status.setAttribute("role","status");header.append(status)}root.append(header);
  const layout=node("div",undefined,"picker-layout"),directory=node("section"),detail=node("section",undefined,"provider-detail"),list=node("div",undefined,"provider-list"),search=node("input");
  search.type="search";search.placeholder="Search "+catalog.length+" services";search.setAttribute("aria-label","Search integrations");directory.append(search,list);layout.append(directory,detail);root.append(layout);
  let selected=catalog.find(p=>p.id===options.provider)||catalog.find(p=>p.id==="composio")||catalog[0];
  function trustedLink(url,text,feedback){const a=node("a",text);try{const u=new URL(url);if(u.protocol!=="https:")return node("span",text);a.href=u.href}catch{return node("span",text)}a.target="_blank";a.rel="noopener noreferrer";if(options.openLink)a.addEventListener("click",e=>{e.preventDefault();Promise.resolve(options.openLink(a.href)).catch(()=>{feedback.textContent="The chat host could not open this link. Open the provider dashboard in your browser."})});return a}
  function drawList(){list.replaceChildren();for(const p of catalog.filter(p=>(p.title+" "+p.description).toLowerCase().includes(search.value.toLowerCase()))){const b=button("",()=>{selected=p;drawList();drawDetail()},"provider-option");b.setAttribute("aria-pressed",String(p.id===selected.id));b.append(node("span",p.title),node("small",p.methods.length>1?p.methods.length+" authentication methods":"Direct credential"));list.append(b)}if(!list.children.length)list.append(node("p","No services matched."))}
  function drawDetail(){
    detail.replaceChildren(node("h3",selected.title),node("p",selected.description));
    const methodLabel=node("label","Authentication method"),select=node("select"),preview=node("div"),feedback=node("p",undefined,"picker-feedback");select.id="integration-auth-method";methodLabel.htmlFor=select.id;feedback.setAttribute("role","status");feedback.setAttribute("aria-live","polite");
    for(const method of selected.methods){const o=node("option",method.label);o.value=method.id;select.append(o)}if(options.method&&selected.methods.some(m=>m.id===options.method)){select.value=options.method;options.method=null}
    const actions=node("div",undefined,"picker-actions"),open=button("Open secure form",async()=>{
      open.disabled=true;feedback.textContent="Opening private setup…";
      try{await options.openSetup(selected.id,select.value)}catch(error){feedback.textContent=error.message||"Setup could not be opened. Sign in as an owner or refresh the connector.";open.disabled=false}
    },"primary");open.dataset.integrationStart="true";if(options.session)open.disabled=options.session.loading||options.session.role!=="owner";actions.append(open);
    if(options.openBrowser)actions.append(button(options.browserLabel||"Open in browser",()=>Promise.resolve(options.openBrowser()).catch(()=>{feedback.textContent="Open the MSO Integrations address in your browser."})));
    function drawGuide(){
      preview.replaceChildren();const method=selected.methods.find(m=>m.id===select.value),guide=method.guidance;
      preview.append(node("label","What you will need"));const fields=node("div",undefined,"provider-fields");for(const f of method.fields)fields.append(node("span",f.label+(f.required?" *":""),"field-tag"));preview.append(fields);
      const d=node("details"),summary=node("summary","Step by step: get this credential"),ol=node("ol");d.open=true;d.append(summary,trustedLink(guide.url,"Open official provider dashboard",feedback));for(const step of guide.steps)ol.append(node("li",step));d.append(ol,trustedLink(guide.reference,"Official documentation",feedback));preview.append(d);
      preview.append(node("p","Ten-minute form · direct HTTPS submission · values never enter the chat. An API check proves access to that endpoint, not every future operation.","picker-note"));
    }
    select.addEventListener("change",drawGuide);detail.append(methodLabel,select,preview,actions,feedback);drawGuide();
  }
  search.addEventListener("input",drawList);drawList();drawDetail();
  return()=>{root.replaceChildren();root.classList.remove("integration")};
}
`;
