import { randomBytes } from "node:crypto";
import { MSO_WIDGET_TOKENS } from "@/lib/presentation/widget-tokens";
import { INTEGRATION_FORM_SCRIPT, INTEGRATION_FORM_STYLE } from "./setup-ui";
import { setupCatalog, SETUP_HUB_SCRIPT, SETUP_HUB_STYLE } from "./setup-hub";

export function integrationSetupPage() {
  const nonce = randomBytes(18).toString("base64");
  const catalog = JSON.stringify(setupCatalog()).replace(/</g, "\\u003c");
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>MSO Integrations</title><style nonce="${nonce}">${MSO_WIDGET_TOKENS}${INTEGRATION_FORM_STYLE}${SETUP_HUB_STYLE}*{box-sizing:border-box}body{margin:0;background:var(--surface);padding:clamp(18px,4vw,50px);font-family:var(--font-body);color:var(--text)}header{max-width:850px;margin:0 auto 24px;font-size:13px}button{border:1px solid var(--sep-strong);border-radius:10px;background:var(--field);color:var(--text);padding:9px 15px;cursor:pointer}select{margin:8px 0 16px}a{color:var(--os-accent)}</style></head><body><header>MSO / Integrations</header><main id="setup" class="integration"><p>Loading integrations…</p></main><noscript>JavaScript is needed for secure credential setup. Use the MSO terminal as an alternative.</noscript><script nonce="${nonce}">${INTEGRATION_FORM_SCRIPT}${SETUP_HUB_SCRIPT}
(async()=>{const root=document.getElementById("setup"),endpoint=location.origin+"/api/integrations/setup",catalog=${catalog};let token=location.hash.slice(1);history.replaceState(null,"",location.pathname+location.search);if(!token){mountIntegrationHub(root,catalog);return}root.replaceChildren(integrationNode("p","Checking secure setup session…"));try{const response=await fetch(endpoint,{method:"POST",credentials:"omit",cache:"no-store",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({action:"schema"}),signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error("This private setup session expired or was already used.");const setup=await response.json();const cleanup=mountIntegrationForm(root,setup,{endpoint,token});token="";window.addEventListener("pagehide",()=>cleanup?.(),{once:true})}catch{token="";root.replaceChildren(integrationNode("h2","Setup session unavailable"),integrationNode("p","The link may have expired or already been used. Your stored credentials have not changed."));const retry=integrationNode("button","Open a new setup session");retry.type="button";retry.onclick=()=>mountIntegrationHub(root,catalog);root.append(retry)}})();</script></body></html>`;
  return { html, csp: `default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; form-action 'none'; base-uri 'none'; frame-ancestors 'none'` };
}
