// Owner-only transfer workbench. The default Integrations screen stays simple;
// this surface is opened explicitly from Integrations sidebar → Transfer & backup.
export const PORTABILITY_SCRIPT=String.raw`
function mountPortability(root,bridge){
  let disposed=false,documentData=null,preview=null,tree=null,active='export';const selected=new Set();root.replaceChildren();root.classList.add('integration','portable-transfer');
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
  const button=(text,fn,cls)=>{const b=el('button',text,cls);b.type='button';b.addEventListener('click',fn);return b};
  const field=(name,type='text')=>{const l=el('label',name),i=el('input');i.type=type;i.autocomplete='off';if(type==='checkbox')l.className='check identity-check';l.append(i);return{l,i}};
  const save=(blob,name)=>{const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
  const selection=()=>scope.value==='all'?undefined:[...selected].map(key=>{const[user,provider,connection]=key.split('|');return{user,provider,connection}});
  const ensureSelection=()=>{const value=selection();if(value&&value.length===0)throw Error('Choose at least one connection.');return value};
  const back=button('← Connections',()=>{cleanup();bridge.back()});const title=el('div',undefined,'transfer-heading');title.append(el('h2','Transfer & backup'),el('p','Backup, move, or restore connections. Advanced tools stay out of the normal connection screen.'));root.append(back,title);
  const tabs=el('div',undefined,'transfer-tabs'),body=el('div');const exportTab=button('Export',()=>{active='export';render()}),importTab=button('Import',()=>{active='import';render()});tabs.setAttribute('role','tablist');for(const b of[exportTab,importTab])b.setAttribute('role','tab');tabs.append(exportTab,importTab);root.append(tabs,body);
  const scope=el('select');for(const[value,text]of[['all','All connections'],['custom','Custom selection…']]){const o=el('option',text);o.value=value;scope.append(o)}
  function scopeTree(){
    const wrap=el('div',undefined,'transfer-tree');if(!tree){wrap.append(el('p','Loading connection list…'));return wrap}
    for(const owner of tree.users){const group=el('section',undefined,'transfer-tree-user'),head=field(owner.label+' · '+owner.id,'checkbox'),keys=[];{const ownerKeys=owner.providers.flatMap(p=>p.connections.map(c=>owner.id+'|'+p.id+'|'+c.id));head.i.checked=ownerKeys.length>0&&ownerKeys.every(key=>selected.has(key));head.i.indeterminate=!head.i.checked&&ownerKeys.some(key=>selected.has(key))}group.append(head.l);
      for(const provider of owner.providers){const pgroup=el('div',undefined,'transfer-tree-provider'),ph=field(provider.title||provider.id,'checkbox'),providerKeys=provider.connections.map(c=>owner.id+'|'+provider.id+'|'+c.id);keys.push(...providerKeys);ph.i.checked=providerKeys.length>0&&providerKeys.every(key=>selected.has(key));ph.i.indeterminate=!ph.i.checked&&providerKeys.some(key=>selected.has(key));pgroup.append(ph.l);
        for(const c of provider.connections){const key=owner.id+'|'+provider.id+'|'+c.id,cf=field(c.label+' · '+c.id+(c.source==='direct'?' · '+c.storedFields+' stored fields':' · authorization metadata only'),'checkbox');cf.i.checked=selected.has(key);cf.i.addEventListener('change',()=>{cf.i.checked?selected.add(key):selected.delete(key);render()});pgroup.append(cf.l)}
        ph.i.addEventListener('change',()=>{for(const key of providerKeys)ph.i.checked?selected.add(key):selected.delete(key);render()});group.append(pgroup)}
      head.i.addEventListener('change',()=>{for(const key of keys)head.i.checked?selected.add(key):selected.delete(key);render()});wrap.append(group)}return wrap;
  }
  function exportView(){
    const card=el('section',undefined,'connection-card transfer-card'),head=el('div');head.append(el('h3','Download backup'),el('p','Encrypted backup is recommended. Plaintext downloads require your MSO password and expire after one use.'));card.append(head);
    const scopeLabel=el('label','Download');scope.setAttribute('aria-label','Export scope');scopeLabel.append(scope);scope.onchange=render;card.append(scopeLabel);if(scope.value==='custom')card.append(scopeTree());
    const format=el('select');for(const[value,text]of[['encrypted','Encrypted JSON · recommended'],['metadata','Metadata JSON · no credential values'],['raw-json','Raw JSON · plaintext credentials'],['env','.env · plaintext credentials']]){const o=el('option',text);o.value=value;format.append(o)}format.value=exportView.format||'encrypted';format.setAttribute('aria-label','Export format');const formatLabel=el('label','Format');formatLabel.append(format);card.append(formatLabel);
    const security=el('div',undefined,'transfer-security'),status=el('p');status.setAttribute('role','status');let pass,repeat,ownerPassword,ack;
    const paint=()=>{exportView.format=format.value;render()};format.addEventListener('change',paint);
    if(format.value==='encrypted'){
      pass=field('Backup passphrase (12+ characters)','password');repeat=field('Confirm backup passphrase','password');pass.i.maxLength=repeat.i.maxLength=1024;security.append(el('p','The file contains selected direct credentials encrypted with your passphrase.'),pass.l,repeat.l);
    }else if(format.value==='raw-json'||format.value==='env'){
      ownerPassword=field('MSO owner password','password');ownerPassword.i.autocomplete='current-password';ownerPassword.i.maxLength=1024;ack=field('I understand this download contains plaintext credentials','checkbox');security.classList.add('danger-zone');security.append(el('strong','Sensitive download'),el('p','MSO will re-authenticate you, issue a 90-second one-time grant, create the file, then invalidate the grant. The password is not stored. Use encrypted JSON when you need a restorable backup.'),ownerPassword.l,ack.l);
    }else security.append(el('p','Metadata only: connection names, methods and configured-field status. No credential values.'));
    card.append(security);
    const download=button(format.value==='metadata'?'Download metadata':format.value==='encrypted'?'Download encrypted backup':'Re-authenticate & download',async()=>{
      download.disabled=true;status.textContent='Preparing download…';
      try{const chosen=ensureSelection();
        if(format.value==='metadata'||format.value==='encrypted'){
          if(format.value==='encrypted'&&(pass.i.value.length<12||pass.i.value!==repeat.i.value))throw Error('Use a matching backup passphrase of at least 12 characters.');
          const response=await bridge.request({action:'export',...(chosen?{selection:chosen}:{}),includeSecrets:format.value==='encrypted',...(format.value==='encrypted'?{passphrase:pass.i.value}:{})});const encrypted=response.bundle.format.endsWith('.encrypted');
          save(new Blob([JSON.stringify(response.bundle,null,2)+'\n'],{type:'application/json'}),'connections-'+new Date().toISOString().slice(0,10)+(encrypted?'.integration-bundle.enc.json':'.integration-bundle.json'));status.textContent=encrypted?'Encrypted backup downloaded.':'Metadata downloaded; it contains no credential values.';
        }else{
          if(!ownerPassword.i.value||!ack.i.checked)throw Error('Enter your MSO password and confirm the plaintext warning.');
          const authorized=await bridge.request({action:'authorize-raw-export',password:ownerPassword.i.value,...(chosen?{selection:chosen}:{})});ownerPassword.i.value='';
          const file=await bridge.download({action:'export-raw',grant:authorized.grant,format:format.value==='env'?'env':'json',...(chosen?{selection:chosen}:{})});save(file.blob,file.filename);ack.i.checked=false;status.textContent='Sensitive file downloaded. The one-time export grant is now invalid.';
        }
      }catch(e){status.textContent=e.message}finally{if(pass)pass.i.value=repeat.i.value='';if(ownerPassword)ownerPassword.i.value='';download.disabled=false}
    },format.value==='raw-json'||format.value==='env'?'danger':'primary');card.append(download,status);body.append(card);
    const hint=el('p','Need to move one credential between owners? Go back to Connections → More on that connection and choose Copy to another owner. Share keeps one owner; Copy creates an independent connection.','transfer-hint');body.append(hint);
  }
  function importView(){
    const card=el('section',undefined,'connection-card transfer-card');card.append(el('h3','Bulk import'),el('p','Upload a metadata or encrypted Integration Bundle. MSO always previews changes first and never overwrites an existing connection.'));
    const file=field('JSON bundle file','file');file.i.accept='.json,application/json';const decrypt=field('Import passphrase (encrypted files only)','password'),prefix=field('User ID prefix (optional)'),policy=el('select'),policyLabel=el('label','Conflicts');decrypt.i.maxLength=1024;prefix.i.placeholder='imported-';prefix.i.maxLength=32;decrypt.l.hidden=true;
    for(const[value,text]of[['skip','Preserve existing connections; skip conflicts'],['error','Stop when a conflict exists']]){const o=el('option',text);o.value=value;policy.append(o)}policyLabel.append(policy);const previewBox=el('pre'),status=el('p');status.setAttribute('role','status');const reviewed=field('I reviewed the preview and accept listed skips / omitted fields','checkbox');
    const reset=()=>{preview=null;previewBox.textContent='';apply.disabled=true;reviewed.i.checked=false};file.i.addEventListener('change',async()=>{reset();documentData=null;decrypt.i.value='';const selectedFile=file.i.files?.[0];if(!selectedFile)return;try{if(selectedFile.size>2*1024*1024)throw Error('JSON file exceeds 2 MiB.');documentData=JSON.parse(await selectedFile.text());decrypt.l.hidden=documentData.format!=='integration-bundle.encrypted';status.textContent='File loaded locally. Preview before applying.'}catch(e){status.textContent=e.message}});prefix.i.addEventListener('input',reset);policy.addEventListener('change',reset);
    const input=()=>({action:'import',document:documentData,prefix:prefix.i.value.trim(),policy:policy.value,...(!decrypt.l.hidden?{passphrase:decrypt.i.value}:{})});const check=button('Preview import',async()=>{if(!documentData){status.textContent='Choose a JSON file first.';return}check.disabled=true;try{preview=await bridge.request(input());previewBox.textContent=JSON.stringify(preview,null,2);apply.disabled=!preview.canApply;status.textContent='Preview only — nothing has changed yet.'}catch(e){reset();status.textContent=e.message}finally{check.disabled=false}});
    const apply=button('Apply import',async()=>{if(!preview||!reviewed.i.checked){status.textContent='Review the preview and confirm first.';return}apply.disabled=check.disabled=true;try{const result=await bridge.request({...input(),apply:true,confirm:preview.planId,acceptWarnings:reviewed.i.checked});previewBox.textContent=JSON.stringify(result,null,2);status.textContent='Import complete. Imported connections are not marked verified; external authorization must be completed again.';documentData=null;file.i.value='';decrypt.i.value='';preview=null}catch(e){status.textContent=e.message;apply.disabled=false}finally{check.disabled=false}},'primary');apply.disabled=true;card.append(file.l,decrypt.l,prefix.l,policyLabel,check,previewBox,reviewed.l,apply,status);body.append(card);
  }
  function render(){if(disposed)return;body.replaceChildren();exportTab.setAttribute('aria-selected',String(active==='export'));importTab.setAttribute('aria-selected',String(active==='import'));active==='export'?exportView():importView()}
  render();bridge.request({action:'tree'}).then(data=>{if(disposed)return;tree=data;for(const owner of tree.users)for(const p of owner.providers)for(const c of p.connections)selected.add(owner.id+'|'+p.id+'|'+c.id);if(active==='export')render()}).catch(e=>{if(!disposed){tree={users:[]};body.prepend(el('p',e.message,'transfer-error'))}});
  function cleanup(){disposed=true;documentData=null;preview=null;selected.clear();root.replaceChildren();root.classList.remove('portable-transfer','integration')}
  return cleanup;
}
`;
export const PORTABILITY_STYLE=String.raw`
.portable-transfer{width:100%;max-width:var(--settings-content-width)!important;margin:auto}.portable-transfer .transfer-heading h2{margin-bottom:var(--space-1)}.portable-transfer .transfer-heading p{margin-top:0}.portable-transfer .transfer-tabs{display:flex;gap:var(--space-1);margin:var(--space-5) 0;border-bottom:var(--stroke) solid var(--border)}
.portable-transfer .transfer-tabs button{border:0;border-radius:0;background:transparent;margin:0;padding:var(--space-2) var(--space-3)}.portable-transfer .transfer-tabs button[aria-selected=true]{border-bottom:var(--stroke-active) solid var(--primary);font-weight:var(--weight-bold);color:var(--settings-action-text)}
.portable-transfer .transfer-card{border:var(--stroke) solid var(--border);border-radius:var(--radius-panel);padding:var(--space-5);background:var(--settings-card);margin-top:0}.portable-transfer .transfer-card>label{display:block;margin:var(--space-4) 0 var(--space-2);font-weight:var(--weight-strong);font-size:var(--type-small)}.portable-transfer select,.portable-transfer input{margin-top:var(--space-2);max-width:100%}
.portable-transfer .transfer-security{margin:var(--space-4) 0;padding:var(--space-4);border-radius:var(--radius-control);background:var(--muted)}.portable-transfer .danger-zone{border:var(--stroke) solid var(--settings-danger-border);background:var(--settings-danger-fill)}
.portable-transfer .identity-check{display:flex;gap:var(--space-2);align-items:center;font-weight:var(--weight-regular)}.portable-transfer .identity-check input{width:var(--icon-size);height:var(--icon-size);margin:0;order:-1;flex:none;accent-color:var(--primary)}
.portable-transfer .transfer-tree{max-height:var(--settings-scroll-max-height);overflow:auto;margin:var(--space-3) 0;padding:var(--space-3);border:var(--stroke) solid var(--border);border-radius:var(--radius-control);background:var(--background)}.portable-transfer .transfer-tree-user{padding:var(--space-2) 0;border-bottom:var(--stroke) solid var(--border)}.portable-transfer .transfer-tree-provider{padding-left:var(--space-6)}.portable-transfer .transfer-tree-provider>.identity-check~.identity-check{padding-left:var(--space-6);color:var(--muted-foreground)}
.portable-transfer pre{max-height:var(--settings-code-max-height);overflow:auto;font:var(--type-caption)/var(--line-body) var(--font-mono);white-space:pre-wrap;overflow-wrap:anywhere;background:var(--muted);border-radius:var(--radius-control);padding:var(--space-3)}.portable-transfer [role=status]{font-size:var(--type-small);overflow-wrap:anywhere}.portable-transfer .transfer-hint{font-size:var(--type-caption);color:var(--muted-foreground);margin-top:var(--space-3)}.portable-transfer button{min-height:var(--control-size);margin:var(--space-2) var(--space-2) var(--space-2) 0}
@container integration (max-width:37.5rem){.portable-transfer .transfer-card{padding:var(--space-4)}.portable-transfer .transfer-tabs button{flex:1}.portable-transfer .transfer-tree-provider,.portable-transfer .transfer-tree-provider>.identity-check~.identity-check{padding-left:var(--space-3)}}
`;
