"use client";
import { useEffect, useMemo, useState } from "react";
import { Copy, Play, RefreshCw, Save, Trash2, Workflow } from "lucide-react";
import type { AppProps } from "@/features/appshell";
import type { WorkflowGraph, WorkflowGraphNode, WorkflowGraphNodeType, WorkflowGraphRun } from "@/lib/contracts/workflow-graph";
import { AppFrame, openWindow } from "@/features/appshell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { WorkflowCanvas } from "./components/workflow-canvas";
import { WorkflowCreateDialog } from "./components/workflow-create-dialog";
import { WorkflowInspector } from "./components/workflow-inspector";
import { WorkflowNodePalette } from "./components/workflow-node-palette";
import { WorkflowRunHistory } from "./components/workflow-run-history";
import { WorkflowRunPanel } from "./components/workflow-run-panel";
import { WorkflowVariablePanel } from "./components/workflow-variable-panel";
import { WorkflowVersionPanel } from "./components/workflow-version-panel";
import { cloneGraph, createFromTemplate, createGraph, deleteGraph, getGraph, listGraphs, resolveNode, runGraph, runStatus, updateGraph } from "./lib/api";

type Definition=Omit<WorkflowGraph,"version"|"id"|"revision"|"createdAt"|"updatedAt">;
type Panel="inspector"|"run"|"history"|"versions"|"variables";
function starterGraph():Definition{return{name:"New Workflow",description:"Private workflow graph.",status:"draft",inputs:{},metadata:{provenance:"user"},nodes:[{id:"manual",name:"Manual Trigger",type:"manual",position:{x:80,y:160},config:{}},{id:"output",name:"Output",type:"output",position:{x:420,y:160},config:{}}],edges:[{id:"edge-start",source:"manual",target:"output"}]};}
export default function WorkflowsApp(_props:AppProps){
 const[graphs,setGraphs]=useState<WorkflowGraph[]>([]),[graph,setGraph]=useState<WorkflowGraph|null>(null),[selected,setSelected]=useState<string|null>(null),[run,setRun]=useState<WorkflowGraphRun|null>(null),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[message,setMessage]=useState(""),[panel,setPanel]=useState<Panel>("inspector"),[search,setSearch]=useState("");
 const node=useMemo(()=>graph?.nodes.find((item)=>item.id===selected)??null,[graph,selected]),runStates=useMemo(()=>new Map(run?.nodes.map((item)=>[item.id,item.state])??[]),[run]),filtered=useMemo(()=>{const q=search.toLowerCase().trim();return graphs.filter((item)=>!q||`${item.name} ${item.metadata.folder??""} ${(item.metadata.tags??[]).join(" ")}`.toLowerCase().includes(q));},[graphs,search]);
 const load=async(selectId?:string)=>{const list=await listGraphs();setGraphs(list);const id=selectId??graph?.id??list[0]?.id;if(id){setGraph(await getGraph(id));setDirty(false);}else{setGraph(null);setDirty(false);}};
 useEffect(()=>{let cancelled=false;void listGraphs().then(async(list)=>{if(cancelled)return;setGraphs(list);if(list[0]){const first=await getGraph(list[0].id);if(!cancelled)setGraph(first);}}).catch((error:unknown)=>{if(!cancelled)setMessage(error instanceof Error?error.message:"Could not load workflows");});return()=>{cancelled=true;};},[]);
 useEffect(()=>{if(!run||run.state!=="running")return;const timer=setInterval(()=>{void runStatus(run.id).then(setRun).catch(()=>undefined);},1600);return()=>clearInterval(timer);},[run]);
 const wrap=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage("");try{await fn();}catch(error){setMessage(error instanceof Error?error.message:"Action failed");}finally{setBusy(false);}};
 const mutate=(next:WorkflowGraph)=>{setGraph(next);setDirty(true);};
 const selectGraph=async(id:string)=>{setGraph(await getGraph(id));setSelected(null);setRun(null);setDirty(false);setPanel("inspector");};
 const createBlank=()=>wrap(async()=>{const next=await createGraph(starterGraph());await load(next.id);setSelected("manual");});
 const createTemplate=(id:string)=>wrap(async()=>{const next=await createFromTemplate(id);await load(next.id);setSelected(next.nodes[0]?.id??null);});
 const createAI=(definition:Definition)=>wrap(async()=>{const next=await createGraph(definition);await load(next.id);setSelected(next.nodes[0]?.id??null);});
 const saveCurrent=async()=>{if(!graph)throw new Error("No workflow selected");if(!dirty)return graph;const next=await updateGraph(graph);setGraph(next);setDirty(false);setGraphs(await listGraphs());return next;};
 const save=()=>graph&&wrap(async()=>{await saveCurrent();setMessage("Saved");});
 const duplicate=()=>graph&&wrap(async()=>{const next=await cloneGraph(graph.id);await load(next.id);});
 const remove=()=>graph&&wrap(async()=>{await deleteGraph(graph);setSelected(null);setRun(null);const list=await listGraphs();setGraphs(list);setGraph(list[0]?await getGraph(list[0].id):null);setDirty(false);});
 const execute=()=>graph&&wrap(async()=>{const saved=await saveCurrent(),receipt=await runGraph(saved.id);setRun(receipt);setPanel("run");});
 const updateNode=(next:WorkflowGraphNode)=>graph&&mutate({...graph,nodes:graph.nodes.map((item)=>item.id===next.id?next:item)});
 const deleteNode=(id:string)=>{if(!graph)return;mutate({...graph,nodes:graph.nodes.filter((item)=>item.id!==id),edges:graph.edges.filter((edge)=>edge.source!==id&&edge.target!==id)});setSelected(null);};
 const addNode=(type:WorkflowGraphNodeType,defaults:Record<string,unknown>)=>{if(!graph)return;const id=`${type}-${crypto.randomUUID().slice(0,8)}`,next:WorkflowGraphNode={id,name:type.replaceAll("_"," ").replace(/\b\w/g,(c)=>c.toUpperCase()),type,position:{x:220+graph.nodes.length*36,y:240+(graph.nodes.length%4)*110},config:structuredClone(defaults)};mutate({...graph,nodes:[...graph.nodes,next]});setSelected(id);setPanel("inspector");};
 const connect=(source:string,target:string,sourceHandle?:string)=>{if(!graph||graph.edges.some((edge)=>edge.source===source&&edge.target===target&&edge.sourceHandle===sourceHandle))return;mutate({...graph,edges:[...graph.edges,{id:`edge-${crypto.randomUUID().slice(0,8)}`,source,target,...(sourceHandle?{sourceHandle}:{})}]});};
 const openNode=async(id:string)=>{if(!graph)return;const resolved=await resolveNode(graph.id,id);openWindow("files-manager",resolved.name,undefined,{path:resolved.path},{multi:true});};
 const panelButton=(value:Panel,label:string)=><button type="button" className={`min-w-0 flex-1 px-1 text-[10px] ${panel===value?"font-semibold text-foreground":"text-muted-foreground"}`} onClick={()=>setPanel(value)}>{label}</button>;
 return <AppFrame safeArea={false} className="h-full" toolbar={<div className="flex h-11 items-center gap-2 border-b px-3"><Workflow className="size-4"/><span className="text-sm font-semibold">Workflows</span>{dirty&&<Badge variant="outline">Unsaved</Badge>}{graph&&<Input className="h-8 max-w-56" value={graph.name} onChange={(e)=>mutate({...graph,name:e.target.value})}/>}<div className="ml-auto flex items-center gap-1"><Button size="sm" variant="ghost" onClick={()=>void load()} disabled={busy}><RefreshCw className="size-3"/></Button><WorkflowCreateDialog onBlank={async()=>{await createBlank();}} onTemplate={async(id)=>{await createTemplate(id);}} onAI={async(definition)=>{await createAI(definition);}}/>{graph&&<><Button size="sm" variant="outline" onClick={()=>void duplicate()} disabled={busy}><Copy className="size-3"/></Button><Button size="sm" variant="outline" onClick={()=>void save()} disabled={busy||!dirty}><Save className="mr-1 size-3"/>Save</Button><Button size="sm" onClick={()=>void execute()} disabled={busy}><Play className="mr-1 size-3"/>Run</Button><Button size="sm" variant="ghost" onClick={()=>void remove()} disabled={busy}><Trash2 className="size-3"/></Button></>}</div></div>}>
  <div className="grid h-full min-h-0 grid-cols-[240px_minmax(0,1fr)_340px]">
   <aside className="min-h-0 border-r bg-muted/10"><div className="space-y-2 border-b p-2"><Input className="h-8" placeholder="Search workflows…" value={search} onChange={(e)=>setSearch(e.target.value)}/><WorkflowCreateDialog onBlank={async()=>{await createBlank();}} onTemplate={async(id)=>{await createTemplate(id);}} onAI={async(definition)=>{await createAI(definition);}}/></div><ScrollArea className="h-[calc(100%-86px)]"><div className="space-y-1 p-2">{filtered.length===0&&<div className="p-3 text-xs text-muted-foreground">No matching private workflows.</div>}{filtered.map((item)=><button key={item.id} type="button" onClick={()=>void wrap(()=>selectGraph(item.id))} className={`w-full rounded-lg border p-2 text-left text-xs ${graph?.id===item.id?"bg-accent":"bg-card"}`}><div className="truncate font-medium">{item.name}</div><div className="mt-1 flex flex-wrap gap-1 text-[10px] text-muted-foreground"><span>{item.status} · {item.nodes.length} nodes</span>{item.metadata.folder&&<span>· {item.metadata.folder}</span>}</div></button>)}</div></ScrollArea></aside>
   <main className="min-h-0 min-w-0 overflow-hidden">{graph?<div className="flex h-full flex-col"><div className="flex h-10 items-center gap-2 border-b px-2"><select className="h-7 rounded border bg-background px-2 text-xs" value={graph.status} onChange={(e)=>mutate({...graph,status:e.target.value as WorkflowGraph["status"]})}><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select><WorkflowNodePalette onAdd={addNode}/><span className="text-[10px] text-muted-foreground">Click output port → input port to connect. Red port = error.</span>{message&&<span className="ml-auto max-w-72 truncate text-[11px] text-muted-foreground">{message}</span>}</div><div className="min-h-0 flex-1 overflow-auto"><WorkflowCanvas graph={graph} selectedId={selected} onSelect={(id)=>{setSelected(id);if(id)setPanel("inspector");}} nodeStates={runStates} onOpen={(id)=>void openNode(id)} onConnect={connect} onMove={(id,position)=>mutate({...graph,nodes:graph.nodes.map((item)=>item.id===id?{...item,position}:item)})}/></div></div>:<div className="flex h-full items-center justify-center text-sm text-muted-foreground">Create or select a workflow.</div>}</main>
   <aside className="min-h-0 border-l"><div className="flex h-10 border-b">{panelButton("inspector","Inspector")}{panelButton("run","Run")}{panelButton("history","History")}{panelButton("versions","Versions")}{panelButton("variables","Vars")}</div><div className="h-[calc(100%-40px)]">{graph&&panel==="inspector"&&<ScrollArea className="h-full"><WorkflowInspector key={node?.id??`graph-${graph.id}`} graph={graph} graphs={graphs} node={node} onNode={updateNode} onDeleteNode={deleteNode} onGraph={mutate}/></ScrollArea>}{panel==="run"&&<WorkflowRunPanel run={run}/>} {graph&&panel==="history"&&<WorkflowRunHistory graph={graph} onSelect={(selectedRun)=>{setRun(selectedRun);setPanel("run");}}/>}{graph&&panel==="versions"&&<WorkflowVersionPanel graph={graph} onRestored={(next)=>{setGraph(next);setDirty(false);void listGraphs().then(setGraphs);}}/>}{panel==="variables"&&<WorkflowVariablePanel/>}</div></aside>
  </div>
 </AppFrame>;
}
