import { timingSafeEqual } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { rateLimited } from "@/lib/host/limits-api";
import { createAgentSession } from "@/lib/agent/session-store";
import { maxScope } from "@/lib/mcp/scope";
import { findActiveWebhookSource } from "@/lib/workflow/graph-triggers";
import { startWorkflowGraph, workflowGraphRunStatus } from "@/lib/workflow/graph-engine";
import { workflowVariableValues } from "@/lib/workflow/variables";
export const runtime="nodejs";export const dynamic="force-dynamic";
function same(a:string,b:string){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y);}
async function payload(req:NextRequest){const length=Number(req.headers.get("content-length")||0);if(length>64*1024)throw new Error("webhook body too large");let body:unknown=null;if(!["GET","HEAD"].includes(req.method)){const text=await req.text();if(Buffer.byteLength(text)>64*1024)throw new Error("webhook body too large");try{body=text?JSON.parse(text):null;}catch{body=text;}}return{method:req.method,query:Object.fromEntries(req.nextUrl.searchParams),httpHeaders:{"content-type":req.headers.get("content-type")||undefined,"user-agent":req.headers.get("user-agent")||undefined,"x-request-id":req.headers.get("x-request-id")||undefined},body};}
async function handle(req:NextRequest,ctx:{params:Promise<{hook:string[]}>}){try{const {hook}=await ctx.params;if(hook.length!==2)return NextResponse.json({error:"webhook_not_found"},{status:404});const source=await findActiveWebhookSource(hook[0]!,hook[1]!);if(!source)return NextResponse.json({error:"webhook_not_found"},{status:404});const methods=Array.isArray(source.node.config.methods)?source.node.config.methods.map(String):["POST"];if(!methods.includes(req.method))return NextResponse.json({error:"method_not_allowed"},{status:405,headers:{Allow:methods.join(", ")}});if(rateLimited(`workflow-webhook:${source.graph.id}:${source.node.id}`,120,60_000))return NextResponse.json({error:"rate_limited"},{status:429});const authVar=typeof source.node.config.authVariable==="string"?source.node.config.authVariable:"";if(authVar){const vars=await workflowVariableValues(source.principal),expected=vars[authVar];if(typeof expected!=="string")return NextResponse.json({error:"webhook_auth_not_configured"},{status:503});const raw=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"")??req.headers.get("x-webhook-token")??"";if(!same(raw,expected))return NextResponse.json({error:"unauthorized"},{status:401});}
 const input=await payload(req),session=await createAgentSession(source.principal,"cli",{title:`Webhook: ${source.graph.name}`,titleSource:"auto"}),{TOOLS_BY_NAME}=await import("@/lib/mcp/tools"),key=(req.headers.get("idempotency-key")||`webhook-${crypto.randomUUID()}`).slice(0,128),context={principal:source.principal,actor:source.principal,sessionId:session.id,scope:maxScope()} as const;const started=await startWorkflowGraph(source.graph,input,key,context,(name)=>TOOLS_BY_NAME.get(name),source.principal,{type:"webhook",nodeId:source.node.id,receivedAt:new Date().toISOString()});if(source.node.config.responseMode!=="lastNode")return NextResponse.json({runId:started.id,state:started.state},{status:202});const done=await workflowGraphRunStatus(source.principal,started.id,25_000),output=[...done.nodes].reverse().find((node)=>node.type==="output"&&node.output!==undefined)?.output;return NextResponse.json({runId:done.id,state:done.state,output},{status:done.state==="failed"?500:200});}catch(error){return NextResponse.json({error:error instanceof Error?error.message.slice(0,300):"webhook_failed"},{status:400});}}
export const GET=handle;export const POST=handle;export const PUT=handle;export const PATCH=handle;export const DELETE=handle;
