import { clean } from "./layout.mjs";
const pick=(rows,id)=>rows?.find((x)=>x.id===id)??null;
const suffix=(id,p)=>id?.startsWith(p)?id.slice(p.length):null;
export const SECTIONS=[{id:"connections",label:"Connections",key:"1"},{id:"users",label:"Users",key:"2"},{id:"catalog",label:"Providers",key:"3"},{id:"transfer",label:"Transfer",key:"4"}];
export function context(stack=[]){const last=(p)=>[...stack].reverse().map((x)=>suffix(x,p)).find((x)=>x!==null)??null;return{user:last("user:"),provider:last("provider:"),connection:last("connection:"),source:last("source:"),auth:last("auth:")};}
const branch=(id,label,hint,preview=[],extra={})=>({id,label,hint,preview,kind:"branch",...extra});
const action=(id,label,hint,preview=[],extra={})=>({id,label,hint,preview,kind:"action",...extra});
const provider=(s,id)=>pick(s.catalog,id),userRow=(s,id)=>pick(s.users,id);
const conn=(s,u,p,c)=>s.connections?.find((x)=>x.user===u&&x.provider===p&&x.id===c)??null;
const sourceRow=(s,p,id)=>provider(s,p)?.sources?.find((x)=>x.id===id)??null;
const methodRow=(s,p,src,id)=>sourceRow(s,p,src)?.methods?.find((x)=>x.id===id)??null;
const storedSummary=(row)=>{const fields=row?.fields||[],stored=fields.filter((f)=>f.stored).length;return `${stored}/${fields.length} credential field(s) configured`;};
function users(s){return (s.users||[]).map((u)=>branch(`user:${u.id}`,u.label,`${u.connectionCount} connection(s)${u.isDefault?" · default":""}`,[`User: ${u.id}`,`Connections: ${u.connectionCount}`,`Default: ${u.isDefault?"yes":"no"}`],{status:u.isDefault?"default":undefined,badge:u.isDefault?"default":undefined}));}
function providers(s,u){return(s.catalog||[]).map((p)=>{const n=(s.connections||[]).filter((c)=>c.user===u&&c.provider===p.id).length;return branch(`provider:${p.id}`,p.title,`${n} connection(s)`,[p.description||"",`Connections for ${u}: ${n}`,`Sources: ${p.sources?.length||0}`],{badge:n?String(n):undefined});});}
function connections(s,u,p){const rows=(s.connections||[]).filter((c)=>c.user===u&&c.provider===p);return[...rows.map((c)=>branch(`connection:${c.id}`,c.label,`${c.source} · ${c.authMethod} · ${c.state}`,[`ID: ${c.id}`,`Source: ${c.source} · Auth: ${c.authMethod} · Scope: ${c.scope}`,`State: ${c.state} · Default: ${c.isDefault?"yes":"no"}`,storedSummary(c)],{status:c.state,badge:c.isDefault?"default":undefined})),branch("new","＋ New connection","choose source/backend and authentication",["Creates metadata first.","Direct credentials are entered only in the private setup form."],{shortcut:"N"})];}
function userActions(s,u){const row=userRow(s,u);return[branch("providers","Connections & providers","manage named accounts/deployments",[`User: ${row?.label||u}`,`Connections: ${row?.connectionCount||0}`]),action("action:user-default","Set as default user","fallback when no folder mapping matches",[`User: ${u}`],{shortcut:"D"}),action("action:user-bind","Use for current folder","longest folder mapping wins",[`Folder: current working directory`,`User: ${u}`]),action("action:user-rename","Rename user","preserve connections and folder mappings"),action("action:user-duplicate","Duplicate user","metadata-only by default",["Direct credentials require a separate explicit opt-in.","Hosted/OAuth identities are not copied."]),action("action:user-delete","Delete user","destructive; exact confirmation",[],{status:"error"})];}
function newConnection(s,p,stack){const ctx=context(stack),last=stack.at(-1);if(last==="new")return(provider(s,p)?.sources||[]).map((src)=>branch(`source:${src.id}`,src.label,`${src.methods?.length||0} auth method(s)`,[src.description||"",src.reference?`Reference: ${src.reference}`:""].filter(Boolean)));if(ctx.source&&last===`source:${ctx.source}`)return(sourceRow(s,p,ctx.source)?.methods||[]).map((m)=>branch(`auth:${m.id}`,m.label,m.scope,[`Scope: ${m.scope}`,`Credential fields: ${(m.fields||[]).length}`,m.guidance?.reference?`Reference: ${m.guidance.reference}`:""].filter(Boolean)));if(ctx.auth&&last===`auth:${ctx.auth}`){const m=methodRow(s,p,ctx.source,ctx.auth);return[action("action:create-connection","Create named connection","label + stable connection ID",[`Provider: ${p}`,`Source: ${ctx.source}`,`Auth: ${ctx.auth}`,`Scope: ${m?.scope||"unknown"}`])];}return null;}
function connectionActions(s,u,p,c){const row=conn(s,u,p,c);if(!row)return[];const base=[`Connection: ${row.label}`,`ID: ${row.id}`,`Source: ${row.source} · Auth: ${row.authMethod} · Scope: ${row.scope}`,`State: ${row.state} · Default: ${row.isDefault?"yes":"no"}`,storedSummary(row)];const out=[];if(row.source==="direct")out.push(action("action:setup","Set / rotate credentials","private browser form",base,{shortcut:"S"}));if(row.source==="composio")out.push(action("action:authorize","Authorize account","Composio hosted authorization",base));out.push(action("action:verify","Verify","live API/auth status",base,{shortcut:"V"}),action("action:route","Route","show exact execution identity",base,{shortcut:"R"}));if(!row.isDefault)out.push(action("action:connection-default","Make default","provider fallback for this user",base,{shortcut:"D"}));if(p==="hostinger"&&row.source==="direct")out.push(branch("mail","Hostinger Mail","orders, mailboxes, aliases and logs",["Uses the selected Hostinger connection.","Secret-shaped response fields remain redacted."]));out.push(action("action:connection-rename","Rename label","metadata only",base),action("action:connection-delete","Delete connection","destructive; exact confirmation",base,{status:"error"}));return out;}
function mailLayer(stack){const last=stack.at(-1);if(last==="mail")return[action("action:mail-orders","Mail orders","list account mail orders"),...["mailboxes","aliases","forwarders","autoreplies","catchalls","webhooks"].map((x)=>action(`action:mail-resource:${x}`,x[0].toUpperCase()+x.slice(1),`list ${x}`)),branch("logs","Mail logs","access/action/inbound/mailbox/outbound")];if(last==="logs")return["access","action","inbound","mailbox-actions","outbound"].map((x)=>action(`action:mail-log:${x}`,x.replaceAll("-"," "),`${x} log`));return null;}
function transferLayer(s){const sc=s.scMigration?.available?[action("action:transfer:sc","Import from SI-Coder",`${s.scMigration.userCount} users · ${s.scMigration.connectionCount} connections detected`,["Automatically detected from ~/.local/bin/sc.","Metadata only: no credential values are copied.","Existing MSO users/connections are preserved."] )]:[];return[...sc,action("action:transfer:metadata","Export metadata JSON","no credential values",["Portable user/provider/connection metadata only.","Safe default for SC/MSO/Baton adapters."],{shortcut:"E"}),action("action:transfer:encrypted","Export encrypted bundle","includes direct credentials",["Passphrase stays in the private browser/TTY flow.","OAuth sessions are never exported."]),action("action:transfer:import","Import bundle","preview before apply",["Conflicts are reviewed before mutation.","Defaults and folder bindings are not silently replaced."],{shortcut:"I"}),action("action:transfer:schema","View portability format","Integration Bundle v1",["schemas/integration-bundle-v1.schema.json"] )];}
export function layer(s,stack=[]){const last=stack.at(-1),ctx=context(stack);if(!last)return[branch("connections","Connections","User → Provider → Connection",["Browse credential identities and actions."],{shortcut:"1"}),branch("users","Credential users","isolated account contexts",["Users group named provider connections."],{shortcut:"2"}),branch("catalog","Provider catalog","sources, auth methods and scope",["Inspect capabilities without exposing credentials."],{shortcut:"3"}),branch("transfer","Transfer",s.scMigration?.available?`SI-Coder detected · ${s.scMigration.userCount} users / ${s.scMigration.connectionCount} connections`:"portable import / export",s.scMigration?.available?["Local SI-Coder metadata is ready to preview/import.","Credential values are never auto-copied."]:["Metadata JSON or encrypted direct credentials."],{shortcut:"4",badge:s.scMigration?.available?"SC":undefined}),action("action:current","Current folder","show resolved credential user/binding"),action("action:quit","Quit","return to shell")];if(last==="connections"||last==="users")return[...users(s),action("action:user-add","＋ Add user","new isolated credential context")];if(last==="transfer")return transferLayer(s);if(last==="catalog")return(s.catalog||[]).map((p)=>branch(`provider:${p.id}`,p.title,`${p.sources?.length||0} source(s)`,[p.description||"",`Sources: ${p.sources?.length||0}`]));if(stack[0]==="catalog"&&ctx.provider&&last===`provider:${ctx.provider}`)return(provider(s,ctx.provider)?.sources||[]).map((src)=>branch(`source:${src.id}`,src.label,`${src.methods?.length||0} method(s)`,[src.description||"",src.reference?`Reference: ${src.reference}`:""].filter(Boolean)));if(stack[0]==="catalog"&&ctx.source&&last===`source:${ctx.source}`)return(sourceRow(s,ctx.provider,ctx.source)?.methods||[]).map((m)=>action(`action:inspect-auth:${m.id}`,m.label,`${m.scope} · ${(m.fields||[]).length} field(s)`,[`Scope: ${m.scope}`,...(m.fields||[]).map((f)=>`${f.label||f.key}: ${f.required?"required":"optional"}`),m.guidance?.reference?`Reference: ${m.guidance.reference}`:""].filter(Boolean)));if(ctx.user&&last===`user:${ctx.user}`)return stack[0]==="users"?userActions(s,ctx.user):providers(s,ctx.user);if(last==="providers"&&ctx.user)return providers(s,ctx.user);if(ctx.provider&&last===`provider:${ctx.provider}`&&stack[0]!=="catalog")return connections(s,ctx.user,ctx.provider);const fresh=newConnection(s,ctx.provider,stack);if(fresh)return fresh;if(ctx.connection&&last===`connection:${ctx.connection}`)return connectionActions(s,ctx.user,ctx.provider,ctx.connection);const mail=mailLayer(stack);if(mail)return mail;return[];}
export function labelFor(s,id,prefix=[]){const ctx=context([...prefix,id]);if(id==="connections")return"Connections";if(id==="users")return"Users";if(id==="catalog")return"Providers";if(id==="transfer")return"Transfer";if(id==="providers")return"Providers";if(id==="new")return"New connection";if(id==="mail")return"Hostinger Mail";if(id==="logs")return"Mail logs";if(id.startsWith("user:"))return userRow(s,ctx.user)?.label||ctx.user;if(id.startsWith("provider:"))return provider(s,ctx.provider)?.title||ctx.provider;if(id.startsWith("connection:"))return conn(s,ctx.user,ctx.provider,ctx.connection)?.label||ctx.connection;if(id.startsWith("source:"))return sourceRow(s,ctx.provider,ctx.source)?.label||ctx.source;if(id.startsWith("auth:"))return methodRow(s,ctx.provider,ctx.source,ctx.auth)?.label||ctx.auth;return clean(id);}
export function columns(s,stack=[]){const out=[];for(let d=0;d<=stack.length;d++){const prefix=stack.slice(0,d);out.push({title:d?labelFor(s,stack[d-1],prefix.slice(0,-1)):"Integrations",nodeId:d?stack[d-1]:"root",items:layer(s,prefix),selectedId:d<stack.length?stack[d]:null});}return out;}
export function activeSection(stack=[],active=null){const root=stack[0]||active?.id;return SECTIONS.some((s)=>s.id===root)?root:null;}
