import { afterAll, describe, expect, it, vi } from "vitest";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
const root=await fs.mkdtemp(path.join(os.tmpdir(),"mso-jev-preserve-"));
process.env.OS_AGENT_SESSIONS_DIR=path.join(root,"sessions");
process.env.OS_AGENT_MEMORY_DIR=path.join(root,"memory");
process.env.OS_AGENT_SESSION_ARCHIVE_DIR=path.join(root,"archives");
process.env.OS_AGENT_SESSION_PRESERVATION_DIR=path.join(root,"preservation");
vi.mock("@/lib/config/store",()=>({hostCredentialStore:()=>({getKey:vi.fn(async()=>"openrouter-key")})}));
vi.mock("@/lib/workflow/jev-session-optimizer",()=>({optimizeSessionWithJev:vi.fn(async(view:{session:{label:string};steps:Array<{ref:string}>})=>({provider:"jev",decision:{id:"session.optimize",version:1,threshold:.5,model:"typesafe/jev-test",latencyMs:4,inputTokens:12,actualCostUsd:.000001},source:{sessionLabel:view.session.label,observedAt:new Date().toISOString(),shownEvents:1,omittedEvents:0},summary:{candidateCount:0,acceptedCount:0,rejectedCount:0},recommendations:[],llmContext:{kind:"mso.jev-session-optimization.v1",instruction:"review",facts:["safe","semantic capsule"],recommendations:[]}}))}));
vi.resetModules();
const store=await import("./session-store");
const preservation=await import("./session-jev-preservation");
afterAll(async()=>{for(const key of ["OS_AGENT_SESSIONS_DIR","OS_AGENT_MEMORY_DIR","OS_AGENT_SESSION_ARCHIVE_DIR","OS_AGENT_SESSION_PRESERVATION_DIR"])delete process.env[key];await fs.rm(root,{recursive:true,force:true});});
describe("JEV session preservation",()=>{
 it("preserves every live session once and reports zero pending",async()=>{
  await store.createAgentSession("principal:jev","cli",{title:"Preserve me"});
  const before=await preservation.jevPreservationStatus();expect(before).toMatchObject({openrouterConnected:true,liveSessions:1,preservedLive:0,pending:1});
  const batch=await preservation.optimizeSessionPreservationBatch({limit:6});expect(batch).toMatchObject({total:1,processed:1,preserved:1,failed:0});
  const after=await preservation.jevPreservationStatus();expect(after).toMatchObject({preservedLive:1,pending:0});
  const record=(await store.listAgentSessions("principal:jev",1))[0]!;
  const full=await store.getAgentSession("principal:jev",record.id);expect(full).toBeTruthy();
  const capsule=await preservation.readLiveJevSessionCapsule(full!);
  expect(capsule).toMatchObject({kind:"mso.jev-session-capsule.v1",sourceBytes:expect.any(Number),sourceSha256:expect.stringMatching(/^[a-f0-9]{64}$/),summary:{semanticStepCount:expect.any(Number)},continuation:{facts:expect.arrayContaining(["semantic capsule"])}});
  const resumed=await store.resumeAgentSession("principal:jev",record.id);
  expect(resumed.jevCapsule).toMatchObject({sourceSha256:capsule!.sourceSha256,sessionLabel:capsule!.sessionLabel});
  const replay=await preservation.optimizeSessionPreservationBatch({limit:6});expect(replay).toMatchObject({processed:1,preserved:0,skipped:1,failed:0});
 });
});
